### ISSUE TITLE
AssertionError with Android 4.4.2 ARM dump

### ISSUE THREAD

**Issue by jahil** [volatilityfoundation/volatility#103]
AssertionError while processing 4.4.2 dump.

linux_pslist:

```
xara@x1 /opt/volatility $ python vol.py --profile=LinuxGolfish-3_4_67ARM -f ~/lime.dump linux_pslist
Volatility Foundation Volatility Framework 2.4
Offset     Name                 Pid             Uid             Gid    DTB        Start Time
---------- -------------------- --------------- --------------- ------ ---------- ----------
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/opt/volatility/volatility/plugins/linux/common.py", line 62, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/opt/volatility/volatility/commands.py", line 127, in execute
    func(outfd, data)
  File "/opt/volatility/volatility/plugins/linux/pslist.py", line 83, in render_text
    if task.mm.pgd == None:
  File "/opt/volatility/volatility/obj.py", line 533, in __getattr__
    result = self.dereference()
  File "/opt/volatility/volatility/obj.py", line 505, in dereference
    offset = self.v()
  File "/opt/volatility/volatility/obj.py", line 439, in v
    data = self.obj_vm.read(self.obj_offset, self.size())
  File "/opt/volatility/volatility/addrspace.py", line 276, in read
    return self._read(addr, length, False)
  File "/opt/volatility/volatility/addrspace.py", line 268, in _read
    assert (position - addr == len(buff)), "Position - address != len(buff) (" + str(position - addr) + " != " + str(len(buff)) + ") in " + self.base.__class__.__name__
AssertionError: Position - address != len(buff) (4 != 0) in LimeAddressSpace
```

limeinfo:

```
xara@x1 /opt/volatility $ python vol.py --profile=LinuxGolfish-3_4_67ARM -f ~/lime.dump limeinfo
Volatility Foundation Volatility Framework 2.4
Memory Start Memory End Size      
------------ ---------- ----------
0x0000000000 0x2f7fffff 0x2f800000
```

linux_banner:

```
xara@x1 /opt/volatility $ python vol.py --profile=LinuxGolfish-3_4_67ARM -f ~/lime.dump linux_banner
Volatility Foundation Volatility Framework 2.4
Linux version 3.4.67-gea97df6 (xara@miner) (gcc version 4.6.x-google 20120106 (prerelease) (GCC) ) #1 PREEMPT Fri Oct 10 02:51:18 GST 2014
```

linux_lsof:

```
xara@x1 /opt/volatility $ python vol.py --profile=LinuxGolfish-3_4_67ARM -f ~/lime.dump linux_lsof
Volatility Foundation Volatility Framework 2.4
Pid      FD       Path
-------- -------- ----
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/opt/volatility/volatility/plugins/linux/common.py", line 62, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/opt/volatility/volatility/commands.py", line 127, in execute
    func(outfd, data)
  File "/opt/volatility/volatility/plugins/linux/lsof.py", line 41, in render_text
    for filp, fd in task.lsof(): 
  File "/opt/volatility/volatility/plugins/overlays/linux/linux.py", line 1524, in lsof
    fds = self.files.get_fds()
  File "/opt/volatility/volatility/obj.py", line 533, in __getattr__
    result = self.dereference()
  File "/opt/volatility/volatility/obj.py", line 505, in dereference
    offset = self.v()
  File "/opt/volatility/volatility/obj.py", line 439, in v
    data = self.obj_vm.read(self.obj_offset, self.size())
  File "/opt/volatility/volatility/addrspace.py", line 276, in read
    return self._read(addr, length, False)
  File "/opt/volatility/volatility/addrspace.py", line 268, in _read
    assert (position - addr == len(buff)), "Position - address != len(buff) (" + str(position - addr) + " != " + str(len(buff)) + ") in " + self.base.__class__.__name__
AssertionError: Position - address != len(buff) (4 != 0) in LimeAddressSpace
```

**Comment by atcuno** [comment]
Hello,

Can you let us know if this is an issue with the latest veresion from Git?

**Comment by 0epsilon0** [comment]
Hello,

I have the same error in the latest version from Git.

**Comment by atcuno** [comment]
Hello,

Is this still an issue with the latest version of Volatility? If so, would it be possible to share the profile and memory sample?

**Comment by sangantnk8** [comment]
Hello,
How I can get the LinuxGolfish-3_4_67ARM profile ? 
Thanks.
