### ISSUE TITLE
linux_apihooks: TypeError: hex() argument can't be converted to hex

### ISSUE THREAD

**Issue by fpusersuggest** [volatilityfoundation/volatility#105]
Hi, after the last closed issue about linux_apihooks I have new error:

    $ ./vol.py linux_apihooks
    Volatility Foundation Volatility Framework 2.4
    Pid     Name             Hook VMA                                 Hook Symbol              Hooked Address Type  Hook Address Hook Library
    ------- ---------------- ---------------------------------------- ------------------------ -------------- ----- ------------ ------------
    Traceback (most recent call last):
      File "./vol.py", line 192, in <module>
        main()
      File "./vol.py", line 183, in main
        command.execute()
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/common.py", line 62, in execute
        commands.Command.execute(self, *args, **kwargs)
      File "/home/user/VOLATILITY/volatility/volatility/commands.py", line 127, in execute
        func(outfd, data)
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/apihooks.py", line 55, in render_text
        for hook_desc, sym_name, addr, hook_type, hook_addr, hookfuncdesc in task.apihook_info():
      File "/home/user/VOLATILITY/volatility/volatility/plugins/overlays/linux/linux.py", line 1371, in apihook_info
        is_hooked = self._is_api_hooked(addr, elf.obj_vm)
      File "/home/user/VOLATILITY/volatility/volatility/plugins/overlays/linux/linux.py", line 1296, in _is_api_hooked
        data = proc_as.read(sym_addr, 24)
      File "/home/user/VOLATILITY/volatility/volatility/addrspace.py", line 276, in read
        return self._read(addr, length, False)
      File "/home/user/VOLATILITY/volatility/volatility/addrspace.py", line 243, in _read
        paddr = self.translate(position)
      File "/home/user/VOLATILITY/volatility/volatility/addrspace.py", line 371, in translate
        return self.vtop(vaddr)
      File "/home/user/VOLATILITY/volatility/volatility/plugins/addrspaces/intel.py", line 130, in vtop
        pgd = self.get_pgd(vaddr)
      File "/home/user/VOLATILITY/volatility/volatility/plugins/addrspaces/intel.py", line 109, in get_pgd
        return self.read_long_phys(pgd_entry)
      File "/home/user/VOLATILITY/volatility/volatility/plugins/addrspaces/intel.py", line 148, in read_long_phys
        return obj.NoneObject("Unable to read_long_phys at " + hex(addr))
    TypeError: hex() argument can't be converted to hex

**Comment by fpusersuggest** [comment]
Hi... this bug is on fedora 20... but I have the same error on fedora 21

# ./vol.py  linux_apihooks
Volatility Foundation Volatility Framework 2.4
Pid     Name             Hook VMA                                 Hook Symbol              Hooked Address Type  Hook Address Hook Library
------- ---------------- ---------------------------------------- ------------------------ -------------- ----- ------------ ------------
Traceback (most recent call last):
  File "./vol.py", line 192, in <module>
    main()
  File "./vol.py", line 183, in main
    command.execute()
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/plugins/linux/common.py", line 63, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/plugins/linux/apihooks.py", line 84, in render_text
    for hook_desc, sym_name, addr, hook_type, hook_addr, hookfuncdesc in task.apihook_info():
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/plugins/overlays/linux/linux.py", line 1456, in apihook_info
    is_hooked = self._is_api_hooked(addr, elf.obj_vm)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/plugins/overlays/linux/linux.py", line 1381, in _is_api_hooked
    data = proc_as.read(sym_addr, 24)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/addrspace.py", line 276, in read
    return self._read(addr, length, False)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/addrspace.py", line 244, in _read
    paddr = self.translate(position)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/addrspace.py", line 371, in translate
    return self.vtop(vaddr)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/plugins/addrspaces/intel.py", line 138, in vtop
    pgd = self.get_pgd(vaddr)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/plugins/addrspaces/intel.py", line 117, in get_pgd
    return self.read_long_phys(pgd_entry)
  File "/media/backbox/f700c131-4d42-4615-995a-68b64c12026e/vol/volatility-master/volatility/plugins/addrspaces/intel.py", line 156, in read_long_phys
    return obj.NoneObject("Unable to read_long_phys at " + hex(addr))
TypeError: hex() argument can't be converted to hex
root@backbox:/vol/volatility-master# cat envirofedo21 
export VOLATILITY_PROFILE=LinuxFedora21ax86
export VOLATILITY_LOCATION=file:////media/backbox/f700c131-4d42-4615-995a-68b64c12026e/dump_f21_03072015.lime
