### ISSUE TITLE
linux_check_syscall: TypeError: unsupported operand type(s) for /: 'NoneObject' and 'int'

### ISSUE THREAD

**Issue by fpusersuggest** [volatilityfoundation/volatility#106]
Hi, I have an other issue with linux plugins.
The affected plugin is linux_check_syscall, the following is the error:

    $ ./vol.py linux_check_syscall
    Volatility Foundation Volatility Framework 2.4
    Table Name Index System Call              Handler Address Symbol                                                      
    ---------- ----- ------------------------ --------------- ------------------------------------------------------------
    Traceback (most recent call last):
      File "./vol.py", line 192, in <module>
        main()
      File "./vol.py", line 183, in main
        command.execute()
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/common.py", line 62, in execute
        commands.Command.execute(self, *args, **kwargs)
      File "/home/user/VOLATILITY/volatility/volatility/commands.py", line 127, in execute
        func(outfd, data)
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/check_syscall.py", line 296, in render_text
        for (tableaddr, table_name, i, idx_name, call_addr, sym_name, _) in data:
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/check_syscall.py", line 291, in calculate
        for (tableaddr, table_name, i, idx_name, call_addr, sym_name, hooked) in self.get_syscalls(index_lines, True): 
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/check_syscall.py", line 188, in get_syscalls
        index_lines = self._find_and_parse_index_file()
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/check_syscall.py", line 264, in _find_and_parse_index_file
        for page in find_file.get_file_contents(inode):
      File "/home/user/VOLATILITY/volatility/volatility/plugins/linux/find_file.py", line 229, in get_file_contents
        idxs = file_size / 4096
    TypeError: unsupported operand type(s) for /: 'NoneObject' and 'int'
    user@localhost volatility$ env|grep VOLATI
    OLDPWD=/home/user/VOLATILITY
    VOLATILITY_LOCATION=file:///home/user/VOLATILITY/MEMORY_SAMPLES/fedora20_14102014.lime
    VOLATILITY_PROFILE=Linuxmiafedora20x86
    PWD=/home/user/VOLATILITY/volatility

**Comment by atcuno** [comment]
What version of Linux is this sample from? I can't find a version where that strucutre does not have a height member.

**Comment by fpusersuggest** [comment]
in the first post at the last third line u can see the sample memory name that is fedora20
