### ISSUE TITLE
Error while running linux_kernel_opened_files or Android profile

### ISSUE THREAD

**Issue by Vic152** [volatilityfoundation/volatility#136]
c:\volatility-2.4>vol.py --profile=LinuxEvo4GARM --filename=C:\vf\Evo4GRodeo.lime linux_kernel_opened_files
Volatility Foundation Volatility Framework 2.4
WARNING : volatility.obj      : Overlay structure tty_struct not present in vtypes
WARNING : volatility.obj      : Overlay structure tty_struct not present in vtypes
Offset (V) Partial File Path

---

WARNING : volatility.obj      : Cant find object hlist_bl_head in profile <volatility.plugins.overlays.linux.linux.LinuxEvo4GARM object at 0x0228FB70>?
Traceback (most recent call last):
  File "C:\volatility-2.4\vol.py", line 192, in <module>
    main()
  File "C:\volatility-2.4\vol.py", line 183, in main
    command.execute()
  File "C:\volatility-2.4\volatility\plugins\linux\common.py", line 62, in execute
    commands.Command.execute(self, _args, *_kwargs)
  File "C:\volatility-2.4\volatility\commands.py", line 127, in execute
    func(outfd, data)
  File "C:\volatility-2.4\volatility\plugins\linux\kernel_opened_files.py", line 126, in render_text
    for dentry in data:
  File "C:\volatility-2.4\volatility\plugins\linux\kernel_opened_files.py", line 117, in calculate
    for dentry_offset in self._compare_filps():
  File "C:\volatility-2.4\volatility\plugins\linux\kernel_opened_files.py", line 97, in _compare_filps
    dcache = self._gather_dcache()
  File "C:\volatility-2.4\volatility\plugins\linux\kernel_opened_files.py", line 78, in _gather_dcache
    arr = obj.Object(theType = "Array", targetType = "hlist_bl_head", offset = d_htable_ptr, vm = self.addr_space, count = loop_max)
  File "C:\volatility-2.4\volatility\obj.py", line 174, in Object
    result = vm.profile.types[theType](offset = offset, vm = vm, name = name, **kwargs)
  File "C:\volatility-2.4\volatility\obj.py", line 594, in __init__
    if self.current.size() == 0:
AttributeError: 'NoneType' object has no attribute 'size'

**Comment by Sebastienbr** [comment]
I know it's an old issue but I have the same problem with CentOS 6.9...

On a CentOS PC, I did compile the module from volatility/tools/linux/ but hlist_bl_head is not in module.dwarf.

Any idea why?

I did use this version of dwarfdump [1] 

Thanks,

Sebastien


[1]: http://pkgs.fedoraproject.org/repo/pkgs/libdwarf/libdwarf-20170709.tar.gz/
