### ISSUE TITLE
Error while running  linux_memmap on Android profile

### ISSUE THREAD

**Issue by Vic152** [volatilityfoundation/volatility#139]
c:\volatility-2.4>vol.py --profile=LinuxEvo4GARM --filename=C:\vf\Evo4GRodeo.lime linux_memmap
Volatility Foundation Volatility Framework 2.4
WARNING : volatility.obj      : Overlay structure tty_struct not present in vtypes
WARNING : volatility.obj      : Overlay structure tty_struct not present in vtypes
Task             Pid      Virtual    Physical         Size
---------------- -------- ---------- ---------- ----------
Traceback (most recent call last):
  File "C:\volatility-2.4\vol.py", line 192, in <module>
    main()
  File "C:\volatility-2.4\vol.py", line 183, in main
    command.execute()
  File "C:\volatility-2.4\volatility\plugins\linux\common.py", line 62, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "C:\volatility-2.4\volatility\commands.py", line 127, in execute
    func(outfd, data)
  File "C:\volatility-2.4\volatility\plugins\linux\pslist.py", line 111, in render_text
    for p in pagedata:
  File "C:\volatility-2.4\volatility\plugins\addrspaces\arm.py", line 164, in get_available_pages
    for i in xrange(0, (2 ** 32) - 1, 4096):
OverflowError: Python int too large to convert to C long

**Comment by atcuno** [comment]
this is not currently supported on Android. I will re-open and comment on this ticket when the support is added. Thank you for the report.
