### ISSUE TITLE
Error while running linux_mount_cache or Android profile

### ISSUE THREAD

**Issue by Vic152** [volatilityfoundation/volatility#140]
c:\volatility-2.4>vol.py --profile=LinuxEvo4GARM --filename=C:\vf\Evo4GRodeo.lime linux_mount_cache
Volatility Foundation Volatility Framework 2.4
WARNING : volatility.obj      : Overlay structure tty_struct not present in vtypes
WARNING : volatility.obj      : Overlay structure tty_struct not present in vtypes
Traceback (most recent call last):
  File "C:\volatility-2.4\vol.py", line 192, in <module>
    main()
  File "C:\volatility-2.4\vol.py", line 183, in main
    command.execute()
  File "C:\volatility-2.4\volatility\plugins\linux\common.py", line 62, in execute
    commands.Command.execute(self, _args, *_kwargs)
  File "C:\volatility-2.4\volatility\commands.py", line 127, in execute
    func(outfd, data)
  File "C:\volatility-2.4\volatility\plugins\linux\mount.py", line 135, in render_text
    for (_sb, dev_name, path, fstype, rr, mnt_string) in data:
ValueError: need more than 2 values to unpack

**Comment by sangantnk8** [comment]
Hello,
How can I get the LinuxEvo4GARM profile ?
Thanks
