### ISSUE TITLE
Struct machine has no member iss

### ISSUE THREAD

**Issue by gleeda** [volatilityfoundation/volatility#169]
```
$ python vol.py -f gleedaMac_Reader.img --profile=MacSnowLeopard_10_6_8_Intelx86 mac_threads

Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "volatility/volatility/plugins/mac/common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "volatility/volatility/commands.py", line 140, in execute
    func(outfd, data)
  File "volatility/volatility/plugins/mac/threads.py", line 382, in render_text
    for proc, thread, stack_start, stack_size, args, registers, is_active, dtraced, debugged, uid in data:
  File "volatility/volatility/plugins/mac/threads.py", line 343, in calculate
    registers = self.get_thread_registers(thread, bit_string)
  File "volatility/volatility/plugins/mac/threads.py", line 291, in get_thread_registers
    registers[reg] = "{0:#10x}".format(getattr(thread.machine.iss.uss.ss_32, reg))
  File "volatility/volatility/obj.py", line 747, in __getattr__
    return self.m(attr)
  File "volatility/volatility/obj.py", line 729, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
AttributeError: Struct machine has no member iss
```

**Comment by atcuno** [comment]
Fixed: https://github.com/volatilityfoundation/volatility/commit/163782b44fc0a596fc3a1ebccb91f79fb4c3f93c
