### ISSUE TITLE
error in mac_recover_filesystem

### ISSUE THREAD

**Issue by gleeda** [volatilityfoundation/volatility#170]
Profile is from https://github.com/volatilityfoundation/profiles/blob/master/Mac/10.6/x86/SnowLeopard_10.6.8_Intel.zip

```
$ python vol.py -f gleedaMac_Reader.img --profile=MacSnowLeopard_10_6_8_Intelx86 mac_recover_filesystem -D OUTPUT

Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "volatility/volatility/plugins/mac/common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "volatility/volatility/commands.py", line 140, in execute
    func(outfd, data)
  File "volatility/volatility/plugins/mac/recover_filesystem.py", line 113, in render_text
    for (num_files) in data: 
  File "volatility/volatility/plugins/mac/recover_filesystem.py", line 105, in calculate
    if self._write_file(vnode, path):
  File "volatility/volatility/plugins/mac/recover_filesystem.py", line 67, in _write_file
    mac_common.write_vnode_to_file(vnode, out_path)                 
  File "volatility/volatility/plugins/mac/common.py", line 209, in write_vnode_to_file
    fd = open(file_path, "wb")
IOError: [Errno 2] No such file or directory: 'OUTPUT/Macintosh HD/private/var/folders/ZW/ZWc7-HiOF8yGfQ4xSXnvbE+++TI/-Caches-/com.apple.QuickLook.thumbnailcache/.dat0284.00f/..namedfork/rsrc'
```

**Comment by gleeda** [comment]
temp fix, but you may want to be more stringent:

```
diff --git a/volatility/plugins/mac/recover_filesystem.py b/volatility/plugins/mac/recover_filesystem.py
index 81573e9..224d144 100644
--- a/volatility/plugins/mac/recover_filesystem.py
+++ b/volatility/plugins/mac/recover_filesystem.py
@@ -61,6 +61,8 @@ class mac_recover_filesystem(mac_common.AbstractMacCommand):
             out_path = os.path.join(self._config.DUMP_DIR, *ents)
 
             # this is the ..namedfork/rsrc files. We currently skip those
+            if out_path.find("..namedfork/rsrc") != -1:
+                return 0
             if os.path.exists(out_path) and os.path.isdir(out_path):
                 shutil.rmtree(out_path) 
 
```

**Comment by atcuno** [comment]
Fixed: https://github.com/volatilityfoundation/volatility/commit/e9cbdcc6c7745adca8370d10d74ed5b1395eee3f
