### ISSUE TITLE
Error running 'apihooks' plugin

### ISSUE THREAD

**Issue by shorejsi** [volatilityfoundation/volatility#175]
Image is Win8SP1x86, pslist, psxview, ssdt, etc. all run fine. Failure presents as:

[a05p8zz@W0147206 W0131278-IntegrationLab]$ vol.py apihooks > Volatility/apihooks2.txt
Volatility Foundation Volatility Framework 2.4
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 5, in <module>
    pkg_resources.run_script('volatility==2.4', 'vol.py')
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/EGG-INFO/scripts/vol.py", line 192, in <module> main()
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/EGG-INFO/scripts/vol.py", line 183, in main command.execute()
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/volatility/commands.py", line 127, in execute func(outfd, data)
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/volatility/plugins/malware/apihooks.py", line 1086, in render_text
    for process, module, hook in data:
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/volatility/plugins/malware/apihooks.py", line 1061, in calculate
    process_space, dll, module_group):
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/volatility/plugins/malware/apihooks.py", line 919, in get_hooks
    self.gather_stuff(addr_space, module)
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/volatility/plugins/malware/apihooks.py", line 855, in gather_stuff
    exports = [(o, module.DllBase + f, n) for o, f, n in module.exports()]
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/volatility/plugins/overlays/windows/pe_vtypes.py", line 531, in exports
    for o, f, n in expdir._exported_functions():
  File "/usr/lib/python2.6/site-packages/volatility-2.4-py2.6.egg/volatility/plugins/overlays/windows/pe_vtypes.py", line 277, in _exported_functions
    ordinal, self.obj_parent.BaseDllName, n))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-10: ordinal not in range(128)

 Cursory examination indicates illegal characters in a DLL name, likely intentional.

**Comment by gleeda** [comment]
Are you using the most recent version from the repository?  If not, please update and try again.

**Comment by gleeda** [comment]
Actually, I can see that this issue has already been addressed in the repository:

https://github.com/volatilityfoundation/volatility/issues/147

Please update to the latest version.  I am going to close this issue out, feel free to reopen if you have another problem.

**Comment by shorejsi** [comment]
Correct diagnosis; updating to the latest solved the problem.  Thanks!
