### ISSUE TITLE
backtrace on mac_threads (struct machine has no member ids)

### ISSUE THREAD

**Issue by iMHLv2** [volatilityfoundation/volatility#189]
```
$ python vol.py -f /Users/mhl/Desktop/dumps/Mac/10.6.8x86.vmem --profile Mac10_6_8x86 mac_threads 
Volatility Foundation Volatility Framework 2.4
Traceback (most recent call last):
 File "vol.py", line 192, in <module>
   main()
 File "vol.py", line 183, in main
   command.execute()
 File "/Users/mhl/GitHub/volatility/volatility/plugins/mac/common.py", line 48, in execute
   commands.Command.execute(self, *args, **kwargs)
 File "/Users/mhl/GitHub/volatility/volatility/commands.py", line 140, in execute
   func(outfd, data)
 File "/Users/mhl/GitHub/volatility/volatility/commands.py", line 275, in render_text
   config = self._config), data)
 File "/Users/mhl/GitHub/volatility/volatility/commands.py", line 269, in _render
   renderer.render(outfd, output)
 File "/Users/mhl/GitHub/volatility/volatility/renderers/text.py", line 115, in render
   grid_depth = grid.visit(None, lambda x, y: max(y, grid.path_depth(x)), 0)
 File "/Users/mhl/GitHub/volatility/volatility/renderers/__init__.py", line 242, in visit
   self.populate()
 File "/Users/mhl/GitHub/volatility/volatility/renderers/__init__.py", line 149, in populate
   for (level, item) in self._generator:
 File "/Users/mhl/GitHub/volatility/volatility/plugins/mac/threads.py", line 388, in generator
   for proc, thread, stack_start, stack_size, args, registers, is_active, dtraced, debugged, uid in data:
 File "/Users/mhl/GitHub/volatility/volatility/plugins/mac/threads.py", line 353, in calculate
   if thread.machine.ids != 0:
 File "/Users/mhl/GitHub/volatility/volatility/obj.py", line 747, in __getattr__
   return self.m(attr)
 File "/Users/mhl/GitHub/volatility/volatility/obj.py", line 729, in m
   raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
AttributeError: Struct machine has no member ids
```

**Comment by atcuno** [comment]
Is this still an issue? If not, can you get the sample avaiable and ping me on chat?
