### ISSUE TITLE
mftparser back trace

### ISSUE THREAD

**Issue by iMHLv2** [volatilityfoundation/volatility#219]
with latest code: 

```
Volatility Foundation Volatility Framework 2.4
Traceback (most recent call last):
  File "/home/USER/volatility/vol.py", line 192, in <module>
    main()
  File "/home/USER/volatility/vol.py", line 183, in main
    command.execute()
  File "/home/USER/volatility/volatility/commands.py", line 140, in execute
    func(outfd, data)
  File "/home/USER/volatility/volatility/plugins/mftparser.py", line 794, in render_body
    outfd.write("0|{0}\n".format(i.body("", mft_entry.RecordNumber, size, offset)))
  File "/home/USER/volatility/volatility/plugins/mftparser.py", line 411, in body
    self.MFTAlteredTime.v(),
  File "/home/USER/volatility/volatility/plugins/overlays/windows/windows.py", line 285, in v
    value = self.as_windows_timestamp()
  File "/home/USER/volatility/volatility/plugins/overlays/windows/windows.py", line 282, in as_windows_timestamp
    return obj.NativeType.v(self)
  File "/home/USER/volatility/volatility/obj.py", line 443, in v
    (val,) = struct.unpack(self.format_string, data)
struct.error: unpack requires a string argument of length 8
```

**Comment by gleeda** [comment]
Yes I've been meaning to fix this.  Someone else asked about it in nyc.  Will fix tonight

--
Jamie Levy (@gleeda)

**Comment by gleeda** [comment]
fixed by 1e66f59fbaa05cb5f4e9ea62c330342a4c349f46

**Comment by iMHLv2** [comment]
hmm, still getting:

```
    Traceback (most recent call last):
  File "/home/mligh/volatility/vol.py", line 192, in <module>
    main()
  File "/home/mligh/volatility/vol.py", line 183, in main
    command.execute()
  File "/home/mligh/volatility/volatility/commands.py", line 140, in execute
    func(outfd, data)
  File "/home/mligh/volatility/volatility/plugins/mftparser.py", line 918, in render_text
    outfd.write("{0}\n".format(str(i)))
  File "/home/mligh/volatility/volatility/plugins/mftparser.py", line 386, in __str__
    str(self.MFTAlteredTime),
  File "/home/mligh/volatility/volatility/plugins/overlays/windows/windows.py", line 292, in __str__
    return "{0}".format(self)
  File "/home/mligh/volatility/volatility/plugins/overlays/windows/windows.py", line 306, in __format__
    dt = self.as_datetime()
  File "/home/mligh/volatility/volatility/plugins/overlays/windows/windows.py", line 296, in as_datetime
    dt = datetime.datetime.utcfromtimestamp(self.v())
  File "/home/mligh/volatility/volatility/plugins/overlays/windows/windows.py", line 285, in v
    value = self.as_windows_timestamp()
  File "/home/mligh/volatility/volatility/plugins/overlays/windows/windows.py", line 282, in as_windows_timestamp
    return obj.NativeType.v(self)
  File "/home/mligh/volatility/volatility/obj.py", line 443, in v
    (val,) = struct.unpack(self.format_string, data)
struct.error: unpack requires a string argument of length 8
```

**Comment by iMHLv2** [comment]
i fixed my issue, but there still appears to be several other places where a timestamp is accessed outside of try/except blocks

**Comment by gleeda** [comment]
*sigh* this is an excellent example of why we need to do adopt what i did in this branch: https://github.com/volatilityfoundation/volatility/tree/objpytest

**Comment by gleeda** [comment]
i think i'm going to just start retesting those changes and commit them instead of adding a million try/excepts...

**Comment by gleeda** [comment]
ok this should be fixed in a91c663519e29ad51b47ab4ce131f42e1a001ebf, can you verify?

**Comment by gleeda** [comment]
actually try now after 4500a946a308f27d774e7e0d94b0b6f6ab9b4637

**Comment by gleeda** [comment]
(you'd have to verify using unified output, i think).  it should be fixed now, gonna close, feel free to reopen
