### ISSUE TITLE
Windows 10 branch -- unable to do anything relating to files [volatility.plugins.obheadercookie]

### ISSUE THREAD

**Issue by andrewjbennett** [volatilityfoundation/volatility#240]
volatility.plugins.obheadercookie: Cannot find nt!ObGetObjectType

This happens when I run any file-related plugins. 

Sometimes I just get the error repeated [eg "handles"], other plugins just crash eg "windows":

    Traceback (most recent call last):
      File "vol.py", line 192, in <module>
        main()
      File "vol.py", line 183, in main
        command.execute()
      File "/home/andrew/src/win10vol/volatility/commands.py", line 127, in execute
        func(outfd, data)
      File "/home/andrew/src/win10vol/volatility/plugins/gui/windows.py", line 48, in render_text
        for winsta, atom_tables in data:
      File "/home/andrew/src/win10vol/volatility/plugins/gui/messagehooks.py", line 68, in calculate
        in atoms.Atoms(self._config).calculate())
      File "/home/andrew/src/win10vol/volatility/plugins/gui/messagehooks.py", line 66, in <genexpr>
        atom_tables = dict((atom_table, winsta)
      File "/home/andrew/src/win10vol/volatility/plugins/gui/atoms.py", line 111, in calculate
        for wndsta in windowstations.WndScan(self._config).calculate():
      File "/home/andrew/src/win10vol/volatility/plugins/gui/windowstations.py", line 57, in calculate
        for wind in self.scan_results(addr_space):
      File "/home/andrew/src/win10vol/volatility/poolscan.py", line 249, in scan
        skip_type_check = skip_type_check)
      File "/home/andrew/src/win10vol/volatility/plugins/overlays/windows/windows.py", line 1136, in         get_object
        return self.get_object_top_down(struct_name, object_type, skip_type_check)
      File "/home/andrew/src/win10vol/volatility/plugins/overlays/windows/windows.py", line 1109, in     get_object_top_down
        header.get_object_type() == object_type):
      File "/home/andrew/src/win10vol/volatility/plugins/overlays/windows/win7.py", line 155, in get_object_type
        return self.type_map.get(int(self.TypeIndex), '')
      File "/home/andrew/src/win10vol/volatility/plugins/overlays/windows/win8.py", line 300, in TypeIndex
        return ((addr >> 8) ^ cook ^ indx) & 0xFF
    TypeError: unsupported operand type(s) for ^: 'int' and 'NoneType'

Running on a memory dump put together as a practice CTF question; I can share it if that will be helpful. Sorry if this isn't a good bug report, let me know if there's anything else you need.

**Comment by iMHLv2** [comment]
Hi Andrew - could you dump the ntoskrnl.exe module from memory and send me a link or email it (michael @ memoryanalysis dot net)? The following command should do that:

$ python vol.py -f [memdump] --profile [profile]  moddump -r ntos -D [dumpdir] 

Thank you!

**Comment by andrewjbennett** [comment]
I emailed you, but here they are: 

https://cloudstor.aarnet.edu.au/plus/index.php/s/bVtkqly6bDwrwUt
https://cloudstor.aarnet.edu.au/plus/index.php/s/8g4bgiy3pRuBmBK

**Comment by iMHLv2** [comment]
Hi Andrew....thanks, I received the files. I may be slightly confused - are you using the Win10 branch to analyze a Win10 memory dump? Or are you just using the Win10 branch to analyze some other system (i.e. Windows 7)?

**Comment by andrewjbennett** [comment]
Win10 branch to analyse a windows 10 memory dump. The dump is here: https://cloudstor.aarnet.edu.au/plus/index.php/s/IIpGbo8UGevACBV

I'm using --profile=Win10x86

**Comment by iMHLv2** [comment]
Interesting...ok...so in the meantime, until I determine a backup method of finding the values we need...you can apply the following patch:

```
diff --git a/volatility/plugins/obheadercookie.py b/volatility/plugins/obheadercookie.py
index fedc0ad..e615dea 100644
--- a/volatility/plugins/obheadercookie.py
+++ b/volatility/plugins/obheadercookie.py
@@ -65,6 +65,9 @@ class ObHeaderCookieStore(object):
         if self._cookie:
             return True
 
+        self._cookie = 0x0F0B899EF
+        return True
+
         if not has_distorm:
             debug.warning("distorm3 module is not installed")
             return False 
```

That should get "handles" plugin, pool scanning plugins (psscan, filescan, mutantscan, etc), and the "windows" plugin working. 

Of course this is just a temporary patch, you'll need to remove the patch before analyzing other Windows 10 samples. But I'll update this issue after writing a short backup method to find the cookie value.

**Comment by iMHLv2** [comment]
Hi Andrew - I'm assuming this worked OK for you? In the newest code, we added a --cookie parameter where you can pass that value on command line instead of having to apply patches. Reopen or email me if you continue to have issues.
