### ISSUE TITLE
psxview plugin error - AttributeError: 'FileAddressSpace' object has no attribute 'translate'

### ISSUE THREAD

**Issue by kevthehermit** [volatilityfoundation/volatility#251]
Ubuntu 14.04 X64
Python 2.7
Volatility 2.5

running this command :

```
thehermit@TechAnarchy:~/opt/volatility-2.5$ python vol.py -f ~/Documents/Images/processfu.img --profile=WinXPSP2x86 timeliner --output=body --output-file=test.body
```

Generates the following error

```
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/thehermit/opt/volatility-2.5/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/timeliner.py", line 168, in render_body
    for line in data:
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/timeliner.py", line 238, in calculate
    for offset, eprocess, ps_sources in psx:
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 216, in calculate
    ps_sources['psscan'] = self.check_psscan()
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 124, in check_psscan
    for p in filescan.PSScan(self._config).calculate())
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 124, in <genexpr>
    for p in filescan.PSScan(self._config).calculate())
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 103, in get_file_offset
    paddr = addr_space.translate(address)
AttributeError: 'FileAddressSpace' object has no attribute 'translate'


```

Tested with 2.4.1 release which works as expected.

**Comment by kevthehermit** [comment]
Looks like this is actually in the psxview plugin

Command
```
thehermit@TechAnarchy:~/opt/volatility-2.5$ python vol.py -f ~/Documents/Images/processfu.img --profile=WinXPSP2x86 psxview
```
Results

```

Volatility Foundation Volatility Framework 2.5
Offset(P)  Name                    PID pslist psscan thrdproc pspcid csrss session deskthrd ExitTime
---------- -------------------- ------ ------ ------ -------- ------ ----- ------- -------- --------
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/thehermit/opt/volatility-2.5/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 437, in render_text
    for offset, process, ps_sources in data:
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 216, in calculate
    ps_sources['psscan'] = self.check_psscan()
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 124, in check_psscan
    for p in filescan.PSScan(self._config).calculate())
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 124, in <genexpr>
    for p in filescan.PSScan(self._config).calculate())
  File "/home/thehermit/opt/volatility-2.5/volatility/plugins/malware/psxview.py", line 103, in get_file_offset
    paddr = addr_space.translate(address)
AttributeError: 'FileAddressSpace' object has no attribute 'translate'
thehermit@TechAnarchy:~/opt/volatility-2.5$ 

```
