### ISSUE TITLE
shutdowntime plugin needs to catch NoneType

### ISSUE THREAD

**Issue by hiddenillusion** [volatilityfoundation/volatility#271]
Traceback:

```
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "/opt/tools/volatility/vol.py", line 192, in <module>
    main()
  File "/opt/tools/volatility/vol.py", line 183, in main
    command.execute()
  File "/opt/tools/volatility/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/opt/tools/volatility/volatility/plugins/registry/shutdown.py", line 99, in render_text
    for result in data:
  File "/opt/tools/volatility/volatility/plugins/registry/shutdown.py", line 74, in calculate
    result["timestamp"] = obj.Object("WinTimeStamp", vm = bufferas, offset = 0, is_utc = True)
  File "/opt/tools/volatility/volatility/obj.py", line 175, in Object
    result = vm.profile.types[theType](offset = offset, vm = vm, name = name, **kwargs)
  File "/opt/tools/volatility/volatility/plugins/overlays/windows/windows.py", line 259, in __init__
    obj.NativeType.__init__(self, theType, offset, vm, format_string = "q", **kwargs)
  File "/opt/tools/volatility/volatility/obj.py", line 424, in __init__
    BaseObject.__init__(self, theType, offset, vm, **kwargs)
  File "/opt/tools/volatility/volatility/obj.py", line 199, in __init__
    if not self.obj_vm.is_valid_address(self.obj_offset):
  File "/opt/tools/volatility/volatility/addrspace.py", line 388, in is_valid_address
    return not (addr < self.base_offset or addr > self.base_offset + len(self.data))
TypeError: object of type 'NoneType' has no len()
```

If I print `result` prior to assigning it to `bufferas`:

```
{'value': None, 'hive': 'SYSTEM', 'key': None, 'valuename': 'ShutdownTime'}
```

**Comment by gleeda** [comment]
thank you for reporting this!  please do a `git pull` and try again and let me know if this is resolved :-)

**Comment by hiddenillusion** [comment]
@gleeda works like a charm, thanks.

**Comment by gleeda** [comment]
cool!  Thanks again for the report!
