### ISSUE TITLE
Getting a RuntimeError after attempting to use my profile.

### ISSUE THREAD

**Issue by bantone** [volatilityfoundation/volatility#291]
I'm on Suse 11 RC3 and have created a memory dump successfully.  Essentially I'm trying to make a memory map.  I'm running the following

> vol.py --plugins=/root/volatility/volatility/plugins/overlays/linux -f /atmos/19fe5ff6-9434-4272-afc2-c5026bcb547a/dump.raw --profile=LinuxSUSE11RC3x64 dumpfiles

The result is this.

> Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 5, in <module>
    pkg_resources.run_script('volatility==2.5', 'vol.py')
  File "/usr/lib64/python2.6/site-packages/pkg_resources.py", line 448, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib64/python2.6/site-packages/pkg_resources.py", line 1166, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib64/python2.6/site-packages/volatility-2.5-py2.6.egg/EGG-INFO/scripts/vol.py", line 192, in <module>
    main()
  File "/usr/local/lib64/python2.6/site-packages/volatility-2.5-py2.6.egg/EGG-INFO/scripts/vol.py", line 183, in main
    command.execute()
  File "/usr/local/lib64/python2.6/site-packages/volatility-2.5-py2.6.egg/volatility/commands.py", line 116, in execute
    if not self.is_valid_profile(profs[self._config.PROFILE]()):
  File "/usr/local/lib64/python2.6/site-packages/volatility-2.5-py2.6.egg/volatility/plugins/overlays/linux/linux.py", line 214, in __init__
    obj.Profile.__init__(self, *args, **kwargs)
  File "/usr/local/lib64/python2.6/site-packages/volatility-2.5-py2.6.egg/volatility/obj.py", line 859, in __init__
    self.reset()
  File "/usr/local/lib64/python2.6/site-packages/volatility-2.5-py2.6.egg/volatility/plugins/overlays/linux/linux.py", line 226, in reset
    self.load_modifications()
  File "/usr/local/lib64/python2.6/site-packages/volatility-2.5-py2.6.egg/volatility/obj.py", line 927, in load_modifications
    raise RuntimeError("Duplicate profile modification name {0} found".format(modname))
RuntimeError: Duplicate profile modification name ELFModification found

Is something wrong with my libelf that is making python throw this exception?

**Comment by atcuno** [comment]
Hey, the problem is your plugins option:

-plugins=/root/volatility/volatility/plugins/overlays/linux

You are pointing it back inside Volatility, which means it is going to pick up all the profiles and code twice, hence the duplicate errors. To use your own profile you just have to copy the zip under volatility/overlay/linux/ and it will pick it up from there.
