### ISSUE TITLE
Mftparser fails on Win2k3SP2x86 .vmsn image

### ISSUE THREAD

**Issue by jpoling-dswrx** [volatilityfoundation/volatility#293]
Using git clone of latest Vol repo. 

`python vol.py -f Snapshot.vmsn --profile=Win2003SP2x86 --kdbg=0x8943e0 mftparser -v --output=body`
> Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/user/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/user/volatility/volatility/plugins/mftparser.py", line 883, in render_body
    for offset, mft_entry, attributes in data:
  File "/home/user/volatility/volatility/plugins/mftparser.py", line 853, in calculate
    offset = 0)
  File "/home/user/volatility/volatility/obj.py", line 175, in Object
    result = vm.profile.types\[theType\](offset = offset, vm = vm, name = name, **kwargs)
  File "/home/user/volatility/volatility/obj.py", line 692, in __init__
    BaseObject.__init__(self, theType, offset, vm, name = name, **kwargs)
  File "/home/user/volatility/volatility/obj.py", line 199, in __init__
    if not self.obj_vm.is_valid_address(self.obj_offset):
  File "/home/user/volatility/volatility/addrspace.py", line 388, in is_valid_address
    return not (addr < self.base_offset or addr > self.base_offset + len(self.data))
TypeError: object of type 'NoneType' has no len()

**Comment by gleeda** [comment]
Is there a way you could give me access to the memory sample to figure out what's going on?

**Comment by jpoling-dswrx** [comment]
Yep. Addressing with you offline.

**Comment by gleeda** [comment]
It's actually a problem with the address space.  I managed to get the output and will send it to you in a bit.

**Comment by gleeda** [comment]
The quick fix is: 

```
diff --git a/volatility/addrspace.py b/volatility/addrspace.py
index 2ce3c4b..7a2c45e 100755
--- a/volatility/addrspace.py
+++ b/volatility/addrspace.py
@@ -385,6 +385,8 @@ class BufferAddressSpace(BaseAddressSpace):
         self.data = data
 
     def is_valid_address(self, addr):
+        if self.data == None:
+            return False
         return not (addr < self.base_offset or addr > self.base_offset + len(self.data))
 
     def read(self, addr, length):
```
Waiting to see if that's how we want to fix it.  We probably should be doing more checking though...

**Comment by gleeda** [comment]
fixed
