### ISSUE TITLE
Yarascan error

### ISSUE THREAD

**Issue by Kamerabuilt** [volatilityfoundation/volatility#299]
Hi, I am using version 2.5, and I get the following errors when using Yarascan with the -Y parameter: 

bt@siftworkstation:/home/volatility# ./vol.py -f ../Desktop/abc.vmem --profile=WinXPSP3x86 yarascan -Y "services" -p1928
Volatility Foundation Volatility Framework 2.5

bt@siftworkstation:/home/volatility# ./vol.py -f ../Desktop/abc.vmem --profile=WinXPSP3x86 yarascan -Y "a" -p1928 
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "./vol.py", line 192, in <module>
    main()
  File "./vol.py", line 183, in main
    command.execute()
  File "/home/sansforensics/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/sansforensics/volatility/volatility/plugins/malware/malfind.py", line 331, in render_text
    for o, addr, hit, content in data:
  File "/home/sansforensics/volatility/volatility/plugins/malware/malfind.py", line 294, in calculate
    for p in process_mem:
  File "/home/sansforensics/volatility/volatility/plugins/malware/malfind.py", line 235, in _scan_process_memory
    for hit, address in scanner.scan():
  File "/home/sansforensics/volatility/volatility/plugins/malware/malfind.py", line 134, in scan
    for match in BaseYaraScanner.scan(self, vad.Start, vad.Length):
  File "/home/sansforensics/volatility/volatility/plugins/malware/malfind.py", line 114, in scan
    for moffset, _name, _value in match.strings:
AttributeError: 'str' object has no attribute 'strings'

**Comment by doomedraven** [comment]
i had this error, is bad installed yara bug, purge yara, and install it `yara libyara3 python-yara`

**Comment by Kamerabuilt** [comment]
Well I used different standalone versions of Volatility with the same error, even under Windows, under Linux, under a VM, etc

**Comment by doomedraven** [comment]
no idea then, but I solved it on my side with reinstall yara, i also patched in that time while i looked for correct solution, do diff of your malfind and this attached, this must works ;) 
[malfind.txt](https://github.com/volatilityfoundation/volatility/files/302850/malfind.txt)

**Comment by Kamerabuilt** [comment]
Is yara seperate than Volatility...?

**Comment by doomedraven** [comment]
yes, is another project

**Comment by Kamerabuilt** [comment]
Ahh that explains a lot ...

**Comment by doomedraven** [comment]
https://github.com/plusvic/yara/releases

**Comment by Kamerabuilt** [comment]
Thanks!

**Comment by gleeda** [comment]
Since it looks like this issue was resolved, I will close it for now.  Please feel free to reopen it if you feel there is still an issue.
