### ISSUE TITLE
timeliner plugin error with var assignment

### ISSUE THREAD

**Issue by cshanahan** [volatilityfoundation/volatility#315]
Hello,
I ran into an error while running the timeliner plugin on an older WinXP SP3 x86 memory sample. I'm running Volatility 2.5 stable from source on a 64-bit Linux system. The memory sample is 2GB and was converted to raw from the system's hibernation file. Other plugins work as expected without error.

> cms@s9:~/bin/Volatility> python vol.py -f xpimage.raw --profile=WinXPSP3x86 timeliner --output=body --output-file=xpimage.body
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/bin/Volatility/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/bin/Volatility/volatility/plugins/timeliner.py", line 168, in render_body
    for line in data:
  File "/bin/Volatility/volatility/plugins/timeliner.py", line 385, in calculate
    for fields in evt.parse_evt_info(name, buf, rawtime = True):
  File "/bin/Volatility/volatility/plugins/evtlogs.py", line 207, in parse_evt_info
    sid_string = self.get_sid_string(rec[end:end + evtlog.SidLength])
  File "/bin/Volatility/volatility/plugins/evtlogs.py", line 128, in get_sid_string
    sid_string = "S-" + "-".join(str(i) for i in (sid.Revision, id_auth) + tuple(sid.SubAuthority))
UnboundLocalError: local variable 'id_auth' referenced before assignment

The plugin completes, but with the above error.

If you need anything to help troubleshoot the issue, please let me know.

/cms

**Comment by gleeda** [comment]
Thank you for the bug report!  it should be fixed as of 1c9e6a50c6942ab7eaefaff74437f7dad2d8ec1f now :-)
