### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by Thestorm77** [volatilityfoundation/volatility#319]
when i try to use modules ldrmodules and malfind i get the following error 

python vol.py --profile=Win10x86 malfind -f /media/sf_Downloads/Dumps/DESKTOP-UNCG505-20160713-184647.raw
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/root/tools/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/root/tools/volatility/volatility/plugins/malware/malfind.py", line 442, in render_text
    for vad, address_space in task.get_vads(vad_filter = task._injection_filter):
  File "/root/tools/volatility/volatility/plugins/overlays/windows/windows.py", line 485, in get_vads
    if not vad.is_valid():
  File "/root/tools/volatility/volatility/plugins/overlays/windows/vad_vtypes.py", line 39, in is_valid
    self.Start < obj.VolMagic(self.obj_vm).MaxAddress.v() and
  File "/root/tools/volatility/volatility/obj.py", line 751, in __getattr__
    return self.m(attr)
  File "/root/tools/volatility/volatility/obj.py", line 733, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))

Not sure what is causing this problem, i am running volatility from Kali 2.0 after cloning the git repository. The memory image is a capture from a win 10 x86 running on virtualbox

**Comment by iMHLv2** [comment]
Thank you very much for reporting...and sorry for the delay. If you git pull master, this should be fixed now (it affected vad plugins on 32-bit win8 and win10...64-bit versions were not affected).
