### ISSUE TITLE
psxview plugin error: 'WindowsHiberFileSpace32' object has no attribute 'translate'

### ISSUE THREAD

**Issue by sabandosoleda** [volatilityfoundation/volatility#361]
Seems like psxview is trying to call a non-existing method on the address space object:

>volatility_2.6_win64_standalone.exe -f FPC2-DELL.raw --profile=Win7SP1x64 --kdbg=0xf8000324a110 psxview
Volatility Foundation Volatility Framework 2.6
Offset(P)          Name                    PID pslist psscan thrdproc pspcid csrss session deskthrd ExitTime
------------------ -------------------- ------ ------ ------ -------- ------ ----- ------- -------- --------
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
  File "vol.py", line 183, in main
  File "volatility\commands.py", line 147, in execute
  File "volatility\plugins\malware\psxview.py", line 441, in render_text
  File "volatility\plugins\malware\psxview.py", line 219, in calculate
  File "volatility\plugins\malware\psxview.py", line 123, in check_pslist
  File "volatility\plugins\malware\psxview.py", line 123, in <genexpr>
  File "volatility\plugins\malware\psxview.py", line 112, in get_file_offset
AttributeError: 'WindowsHiberFileSpace32' object has no attribute 'translate'
Failed to execute script vol

**Comment by DaffySpider** [comment]
I am also facing this issue, any fix for it yet ?
