### ISSUE TITLE
recover file error

### ISSUE THREAD

**Issue by eyahoww** [volatilityfoundation/volatility#366]
Hi
my system is ubuntu 14.04 and 16.04, volatility 2.5. (other volatility version is compiled faile, because other version occurs RADIX TREE MAX TAGS error)
And excuted linux_find_file and linux_recover_filesystems, but its falied and create 0byte file.
this is error message.
i need help.

root@ubuntu:~/volatility-master# python vol.py -f /dump_mem/ram.lime --profile=LinuxinsungARM linux_find_file -i 0xc4926e28 -O /home/eyahoww/Downloads/insung/dump_dex
Volatility Foundation Volatility Framework 2.5
WARNING : volatility.debug    : Cant find object radix_tree_node in profile <volatility.plugins.overlays.linux.linux.LinuxinsungARM object at 0x7f50e7441b90>?
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/root/volatility-master/volatility/plugins/linux/common.py", line 63, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/root/volatility-master/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/root/volatility-master/volatility/plugins/linux/find_file.py", line 137, in render_text
    for (file_path, inode) in data:
  File "/root/volatility-master/volatility/plugins/linux/find_file.py", line 126, in calculate
    for page in self.get_file_contents(inode):        
  File "/root/volatility-master/volatility/plugins/linux/find_file.py", line 238, in get_file_contents
    data = self.get_page_contents(inode, idx)
  File "/root/volatility-master/volatility/plugins/linux/find_file.py", line 202, in get_page_contents
    page_addr = self.find_get_page(inode, idx)
  File "/root/volatility-master/volatility/plugins/linux/find_file.py", line 193, in find_get_page
    page = self.radix_tree_lookup_slot(inode.i_mapping.page_tree, offset)
  File "/root/volatility-master/volatility/plugins/linux/find_file.py", line 170, in radix_tree_lookup_slot
    height = node.height
AttributeError: 'NoneType' object has no attribute 'height'

**Comment by atcuno** [comment]
Hello,

Could you please update to the latest version of Volatility? This issue
should have been fixed in this patch:

https://github.com/volatilityfoundation/volatility/commit/324dd7341d7e1a4e0734dfec69f86c823b8cb02c

Thanks,
Andrew (@attrc)
