### ISSUE TITLE
volatility.debug file does not existed

### ISSUE THREAD

**Issue by SawsanAlodibat** [volatilityfoundation/volatility#379]
when I'm trying to run the following command on win 10:

volatility_2.6_win64_standalone.exe --plugins=myplugins --profile=Win10x64 -f 20170224.mem myplugin
 I get this error:

Traceback (most recent call last):
  File "vol.py", line 192, in <module>
  File "vol.py", line 183, in main
  File "volatility\commands.py", line 147, in execute
  File "volatility\commands.py", line 282, in render_text
  File "volatility\commands.py", line 273, in _render
  File "volatility\commands.py", line 270, in unified_output
NotImplementedError: Rendering using the unified output format has not been implemented for this plugin.
Failed to execute script vol

**Comment by iMHLv2** [comment]
What's your plugin look like? Have you implemented `render_text`?

**Comment by SawsanAlodibat** [comment]
No i'm just running the command of plugin based on standalone executable release of volatility on windows 10 platform.


Please help me in resolving this issue I'm not using vol.py in the source code module installer, Instead I use standalone executable file


Thanks

**Comment by gleeda** [comment]
This seems to be an issue with your plugin `myplugin`.  What does that plugin look like?  You are most likely missing `render_text`

**Comment by elvispopovic** [comment]
So, another NOTHING. Guys, do you have answers or not?

**Comment by jared703** [comment]
@elvispopovic the Volatility devs do their best at keeping this awesome framework moving forward. Instead of complaining you could take a look at the issue and propose a solution yourself. Open source is good like that.

**Comment by mabj** [comment]
"volatility.debug file does not existed" 
I usually get this message back when the process memory file is missing. For instance: 
<pre>
$ /usr/local/bin/vol.py --plugins=./Extractors/Volatility/ -f ./samples/FAKE.dump  --profile Win7SP1x86 myplugin
Volatility Foundation Volatility Framework 2.6
ERROR   : volatility.debug    : The requested file doesn't exist
</pre> 

Just double check if the memdump file really exists.

**Comment by mabj** [comment]
"NotImplementedError: Rendering using the unified output format has not been implemented for this plugin."

In this case, I think, you just forgot to implement the "render_text" method as mentioned by @gleeda.

**Comment by sajious** [comment]
Just Run cmd as administrator. :)
