### ISSUE TITLE
Output xlsx illegal character error

### ISSUE THREAD

**Issue by rawtalent06** [volatilityfoundation/volatility#386]
When using the command line below, I am getting the following error:  "openpyxl.exceptions.IllegalCharacterError" (see the full error at the bottom).  I am not too surprised because of the command I am running but I am trying to get around this error.  

_vol.py netscan -f test.dmp --output=xlsx --output-file=testDir/test.xlsx_

I need a way to sanitize the data before it is written to the xlsx file and this appears to only be possible if I edit volatility/renderers/xlsx.py.  However, with this involving editing a class file I wanted to know if we can get something added in a future release to fix this error.

**Error:**
NEW COMMAND. Run filescan
Volatility Foundation Volatility Framework 2.5
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 145, in execute
    func(outfd, data)
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 324, in render_xlsx
    self._render(outfd, XLSXRenderer(self.text_cell_renderers, self._config), data)
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 274, in _render
    renderer.render(outfd, output)
  File "/usr/lib/python2.7/dist-packages/volatility/renderers/xlsx.py", line 47, in render
    grid.visit(None, self._add_row, {None: 0}) 
  File "/usr/lib/python2.7/dist-packages/volatility/renderers/__init__.py", line 260, in visit
    accumulator = self._visit(children, function, accumulator, sort_key)
  File "/usr/lib/python2.7/dist-packages/volatility/renderers/__init__.py", line 267, in _visit
    accumulator = function(n, accumulator)
  File "/usr/lib/python2.7/dist-packages/volatility/renderers/xlsx.py", line 37, in _add_row
    self._ws.append(list(node.values))
  File "/usr/local/lib/python2.7/dist-packages/openpyxl-2.1.2-py2.7.egg/openpyxl/writer/dump_lxml.py", line 117, in append
    cell.value = value
  File "/usr/local/lib/python2.7/dist-packages/openpyxl-2.1.2-py2.7.egg/openpyxl/cell/cell.py", line 353, in value
    self.bind_value(value)
  File "/usr/local/lib/python2.7/dist-packages/openpyxl-2.1.2-py2.7.egg/openpyxl/cell/cell.py", line 267, in bind_value
    self.set_explicit_value(value, self.data_type)
  File "/usr/local/lib/python2.7/dist-packages/openpyxl-2.1.2-py2.7.egg/openpyxl/cell/cell.py", line 238, in set_explicit_value
    value = self.check_string(value)
  File "/usr/local/lib/python2.7/dist-packages/openpyxl-2.1.2-py2.7.egg/openpyxl/cell/cell.py", line 223, in check_string
    raise IllegalCharacterError
openpyxl.exceptions.IllegalCharacterError

**Comment by gleeda** [comment]
I'll take a look it soon.  In the meantime, you can maybe output to csv format an import into Excel.

**Comment by rawtalent06** [comment]
I have been using the csv output but without field delimiters, it isn't easy to parse the results into the correct columns.  Outputting to CSV does not produce this error and I can then take that data and strip the illegal characters and then output to xlsx but I am back to the columns not extracting correct in Excel.

On the website (i.e. https://github.com/volatilityfoundation/volatility/wiki/Unified-Output), I saw there is a new renderer called "quick" which is exactly what I need.  However, I am not seeing that option as part of my installation or maybe its only specific to certain plugins and not all.  Is there a special install in order to see that renderer?

**Comment by rawtalent06** [comment]
I was able to get something working when editing the file volatility/renderers/xlsx.py.  Below are the code changes I made to the file by adding a new function called sanitize_text(), updating the function _add_row() to call it, and adding "import json" at the top.  I am not certain if this would be applicable for all scenarios but I am about to run several plugins using this updated file to see if I have any issues.

    # This strips all illegal characters from the data
    def sanitize_text(self, data):
        print data
        replace_with = {
            u'\u2018': '\'',
            u'\u2019': '\'',
            u'\u201c': '"',
            u'\u201d': '"'
        }

        if (data is not None) and (len(data) != 0):
            for uni_char in replace_with.keys():
                for item in data:
                   if isinstance(item, basestring):
                       item = item.replace(uni_char, replace_with.get(uni_char))

        return data

    def _add_row(self, node, data):
        accumulator = data
        accumulator[node] = max(accumulator.values()) + 1
        self._ws.append(self.sanitize_text(list(node.values)))
        return accumulator

**Comment by atcuno** [comment]
@gleeda just had this trigger on a sample I was analyzing with filescan in the xlsx mode. It looks like the filename had some unicode junk in it
