### ISSUE TITLE
how to resolve Struct VOLATILITY_MAGIC has no member KDBG error

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/volatility#387]
when i perform

    python vol.py imageinfo -f dump/linux-sample-1.bin

command it gives me a output

    Volatility Foundation Volatility Framework 2.6
    INFO : volatility.debug : Determining profile based on KDBG search...
    Suggested Profile(s) : No suggestion (Instantiated with Linuxbookx64)
    AS Layer1 : LinuxAMD64PagedMemory (Kernel AS)
    AS Layer2 : FileAddressSpace (/home/ram/Ankit/Volatility/volatility-master/dump/linux-sample-1.bin)
    PAE type : No PAE
    DTB : 0x1605000L

how to get  Suggested Profile(s) answer
and following error

    Traceback (most recent call last):
    File "vol.py", line 192, in
    main()
    File "vol.py", line 183, in main
    command.execute()
    File "/home/ram/Ankit/Volatility/volatility-master/volatility/commands.py", line 147, in execute
    func(outfd, data)
    File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/imageinfo.py", line 45, in render_text
    for k, t, v in data:
    File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/imageinfo.py", line 103, in calculate
    kdbg = volmagic.KDBG.v()
    File "/home/ram/Ankit/Volatility/volatility-master/volatility/obj.py", line 751, in getattr
    return self.m(attr)
    File "/home/ram/Ankit/Volatility/volatility-master/volatility/obj.py", line 733, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
    AttributeError: Struct VOLATILITY_MAGIC has no member KDBG

**Comment by gleeda** [comment]
Fixed in e6c36e2ef104e1ab5c2830864a354a692f749678  Please update.
