### ISSUE TITLE
Error in  linux_netscan plugin

### ISSUE THREAD

**Issue by AnkitKundariya** [volatilityfoundation/volatility#393]
> python vol.py --profile=Linuxbookx64 -f dump/linux/linux-sample-1.bin linux_netscan

```

Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/linux/common.py", line 64, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/home/ram/Ankit/Volatility/volatility-master/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/linux/netscan.py", line 119, in render_text
    for (isock, proto, saddr, sport, daddr, dport, state) in data:
  File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/linux/netscan.py", line 93, in calculate
    for _, address in scanner.scan(start_offset = kernel_start):
  File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/malware/malfind.py", line 166, in scan
    for match in BaseYaraScanner.scan(self, contiguous_offset, total_length):
  File "/home/ram/Ankit/Volatility/volatility-master/volatility/plugins/malware/malfind.py", line 114, in scan
    for moffset, _name, _value in match.strings:
AttributeError: 'str' object has no attribute 'strings'

```

@gleeda

**Comment by bneuburg** [comment]
That sounds like the version of yara you have installed is not recent enought, make sure you have at least python-yara 3.4

C.f. volatilityfoundation/volatility#257, second and last comment.

**Comment by AnkitKundariya** [comment]
ok all the main problem is yara package just uninstall your previous yara instillation and execute  following command in terminal 
`sudo pip install yara-python`

and than perform ` linux_netscan` plug in and it's work fine

thanks @bneuburg
