### ISSUE TITLE
mac_check_syscalls, mac_arp, and mac_ip_filters not working on newer Mac memory samples.

### ISSUE THREAD

**Issue by daga480** [volatilityfoundation/volatility#401]
I get the following python errors in both SIFT and Windows versions of Volatility for certain mac_ commands (Volatility 2.6).  All other commands I've tried work fine in both platforms.  Tested this on OSX 10.11.4 and 10.12.3 samples.

Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "C:\Users\Investigator\Downloads\volatility-master\vol.py", line 192, in <module>
    main()
  File "C:\Users\Investigator\Downloads\volatility-master\vol.py", line 183, in main
    command.execute()
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\commands.py", line 147, in execute
    func(outfd, data)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\check_syscall_table.py", line 114, in render_text
    for (_, table_name, i, call_addr, sym_name, hooked) in data:
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\check_syscall_table.py", line 75, in calculate
    sysents = obj.Object(theType = "Array", offset = table_addr, vm = self.addr_space, count = nsysent, targetType = "sysent")
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\obj.py", line 171, in Object
    offset = int(offset)
TypeError: int() argument must be a string or a number, not 'NoneType'

Volatility Foundation Volatility Framework 2.6
Source IP                Dest. IP                    Name           Sent               Recv                     Time                 Exp.    Delta
------------------------ ------------------------ ---------- ------------------ ------------------ ------------------------------ ---------- -----
Traceback (most recent call last):
  File "C:\Users\Investigator\Downloads\volatility-master\vol.py", line 192, in <module>
    main()
  File "C:\Users\Investigator\Downloads\volatility-master\vol.py", line 183, in main
    command.execute()
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\commands.py", line 147, in execute
    func(outfd, data)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\route.py", line 124, in render_text 
    for rt in data:
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\arp.py", line 38, in calculate
    ptr = obj.Object("Pointer", offset = arp_addr, vm = self.addr_space)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\obj.py", line 171, in Object
    offset = int(offset)
TypeError: int() argument must be a string or a number, not 'NoneType'

Volatility Foundation Volatility Framework 2.6
Context    Filter           Pointer            Status
---------- ---------------- ------------------ ------
Traceback (most recent call last):
  File "C:\Users\Investigator\Downloads\volatility-master\vol.py", line 192, in <module>
    main()
  File "C:\Users\Investigator\Downloads\volatility-master\vol.py", line 183, in main
    command.execute()
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\commands.py", line 147, in execute
    func(outfd, data)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\ip_filters.py", line 95, in render_text
    for (good, context, fname, ptr) in data:
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\plugins\mac\ip_filters.py", line 55, in calculate
    plist = obj.Object("ipfilter_list", offset = list_addr, vm = self.addr_space)
  File "C:\Users\Investigator\Downloads\volatility-master\volatility\obj.py", line 171, in Object
    offset = int(offset)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by iMHLv2** [comment]
Hello - please try downloading your profiles again from https://github.com/volatilityfoundation/profiles/tree/master/Mac. We recently applied some updates to profiles that were missing critical symbols that these plugins depend on. Let us know if that helps.

**Comment by daga480** [comment]
Thanks that did work for mac_arp and mac_check_syscalls.  Mac_ip_filters didn't error but also didn't have any results.  Others like mac_threads and mac_threads_simple still get similar python errors (below).  

Is there something new we need to do to create Mac profiles?  I noticed new ones posted for 10.12.3, where I made my own for that earlier, and was just wondering if the profile creation process has changed for Sierra?  Also wondering if I should re-run scripts that used the previous profile.

Volatility Foundation Volatility Framework 2.6
PID      Name             Start Time                       Priority Start Function     Function Map
-------- ---------------- -------------------------------- -------- ------------------ ------------
Traceback (most recent call last):
  File "C:\Users\investigator\Downloads\volatility-master\vol.py", line 192, in <module>
    main()
  File "C:\Users\investigator\Downloads\volatility-master\vol.py", line 183, in main
    command.execute()
  File "C:\Users\investigator\Downloads\volatility-master\volatility\plugins\mac\common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\commands.py", line 147, in execute
    func(outfd, data)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\plugins\mac\threads_simple.py", line 96, in render_text
    th.priority,
  File "C:\Users\investigator\Downloads\volatility-master\volatility\obj.py", line 751, in __getattr__
    return self.m(attr)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\obj.py", line 733, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
AttributeError: Struct thread has no member priority


Volatility Foundation Volatility Framework 2.6
Offset             Pid      Tid      UID      State                          Is Active? Options
ddr   Stack Size (bytes) HW Debugged DTraced Arguments
------------------ -------- -------- -------- ------------------------------ ---------- ---------------------------
----- ------------------ ----------- ------- ---------
Traceback (most recent call last):
  File "C:\Users\investigator\Downloads\volatility-master\vol.py", line 192, in <module>
    main()
  File "C:\Users\investigator\Downloads\volatility-master\vol.py", line 183, in main
    command.execute()
  File "C:\Users\investigator\Downloads\volatility-master\volatility\plugins\mac\common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\commands.py", line 147, in execute
    func(outfd, data)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\plugins\mac\threads.py", line 426, in render_text
    for proc, thread, stack_start, stack_size, args, registers, is_active, dtraced, debugged, uid in data:
  File "C:\Users\investigator\Downloads\volatility-master\volatility\plugins\mac\threads.py", line 322, in calculate
    maps = self.get_stack_map(proc, thread_list, bit_string)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\plugins\mac\threads.py", line 219, in get_stack_map
    map_type = str(dict_alias.get(int(map.alias), "UNKNOWN"))
  File "C:\Users\investigator\Downloads\volatility-master\volatility\obj.py", line 541, in __getattr__
    return getattr(result, attr)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\obj.py", line 751, in __getattr__
    return self.m(attr)
  File "C:\Users\investigator\Downloads\volatility-master\volatility\obj.py", line 733, in m
    raise AttributeError("Struct {0} has no member {1}".format(self.obj_name, attr))
AttributeError: Struct next has no member alias
