### ISSUE TITLE
Windows 10 x64 psscan error: ^: 'int' and 'NoneType'

### ISSUE THREAD

**Issue by gleeda** [volatilityfoundation/volatility#436]
Note: `Win10x64_14393` is the correct profile for this memory sample.

```
$ python vol.py -f Windows\ 10\ x64-c4aa8f1b.vmem --profile=Win10x64_14393 psscan
Volatility Foundation Volatility Framework 2.6
Offset(P)          Name                PID   PPID PDB
Time created                   Time exited
------------------ ---------------- ------ ------ ------------------
------------------------------ ------------------------------
WARNING : volatility.debug    : Cannot find nt!ObGetObjectType
WARNING : volatility.debug    : Cannot find nt!ObGetObjectType
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "volatility/volatility/plugins/filescan.py", line 423, in render_text
    for eprocess in data:
  File "volatility/volatility/poolscan.py", line 252, in scan
    skip_type_check = skip_type_check)
  File "volatility/volatility/plugins/overlays/windows/windows.py", line
1144, in get_object
    return self.get_object_top_down(struct_name, object_type,
skip_type_check)
  File "volatility/volatility/plugins/overlays/windows/windows.py", line
1117, in get_object_top_down
    header.get_object_type() == object_type):
  File "volatility/volatility/plugins/overlays/windows/win7.py", line
155, in get_object_type
    return self.type_map.get(int(self.TypeIndex), '')
  File "volatility/volatility/plugins/overlays/windows/win10.py", line
279, in TypeIndex
    return ((addr >> 8) ^ cook ^ indx) & 0xFF
TypeError: unsupported operand type(s) for ^: 'int' and 'NoneType'
```

**Comment by iMHLv2** [comment]
What's the GUID for that ntoskrnl.exe?

**Comment by gleeda** [comment]
3E1470698B694782ADAE95555171FC1F1

**Comment by iMHLv2** [comment]
So the warning `Cannot find nt!ObGetObjectType` indicates that we're able to find the NT module in memory, but can't parse its export table (thus we can't find the cookie value, thus we can't decode the object header)....all of which is required for the scanning plugins for that OS version. If you're able to moddump the NT module (with and without `--memory`, because I don't know which one would be more complete) we could try to find the function using symbols rather than the export table...and then you could get psscan working by specifying `--cookie=<value that we find>` at that point.

**Comment by iMHLv2** [comment]
Actually, I can tell that the RVA for that GUID is `0x3a6460` so if you just add that to the base address of the NT module, then you should be able to supply that absolute address to `--cookie`. That's probably worth a shot before extracting things.

**Comment by gleeda** [comment]
Sadly, the `--cookie` option doesn't work with the value you gave:

```
$ python vol.py -f Win10x64_14393.vmem --profile=Win10x64_14393 psscan --cookie=0xfffff801761c5460
Volatility Foundation Volatility Framework 2.6
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
0x000099065aae031e 56004F2}         51...8 42...3 0x92e0fffffff00000    
```

I get the same thing with just the RVA as well:

```
$ python vol.py -f Win10x64_14393.vmem --profile=Win10x64_14393 psscan --cookie=0x3a6460
Volatility Foundation Volatility Framework 2.6
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
0x000099065aae031e 56004F2}         51...8 42...3 0x92e0fffffff00000 
```

This is also after I updated the vtypes, since they were just slightly different.

**Comment by gleeda** [comment]
Just in case...

[ntoskrnl.exe.zip](https://github.com/volatilityfoundation/volatility/files/1095498/ntoskrnl.exe.zip)

**Comment by iMHLv2** [comment]
Thanks...yeah, the RVA 0x3a6460 is correct for that file. Can you `dd` the address `0xfffff801761c5460` in volshell and paste the output?

**Comment by gleeda** [comment]
```
In [1]: dd(0xfffff801761c5460)
fffff801761c5460  00000800 80000000 00000200 80000000
fffff801761c5470  00000800 00000000 00000200 00000000
fffff801761c5480  00000000 00000000 00000018 80000000
fffff801761c5490  00000018 00000000 00000018 00000000
fffff801761c54a0  00000818 80000000 00000218 80000000
fffff801761c54b0  00000818 00000000 00000218 00000000
fffff801761c54c0  00000000 00000000 00000000 80000000
fffff801761c54d0  00000000 00000000 00000000 00000000
```

**Comment by iMHLv2** [comment]
Definitely doesn't look like a cookie value at that address. Can you `moddump --base=0xfffff80175e1f000` (with and without `--memory`) and post those two?

**Comment by gleeda** [comment]
[ntos_dumped.zip](https://github.com/volatilityfoundation/volatility/files/1095698/ntos_dumped.zip)

**Comment by gleeda** [comment]
OK, i got it working with `--cookie=0x4ddbae87`... I'm not sure what was broken yet, but I'll document it here in a sec.  I had to manually find the function and trace through the cookie code in the `win10.py` and got the this address, which works with `psscan`

**Comment by iMHLv2** [comment]
Ah nice. Well one thing that was broken is I told you the `--cookie` takes the address of `nt!ObHeaderCookie` when it actually takes the cookie value (dword stored at `nt!ObHeaderCookie`) - sorry. However, I'm not sure why we don't see the cookie value at the alleged base + RVA. The inability to find the exported function in the first place is likely due to paging of the PE header values (I can't parse the EAT in either of the modules you dumped).

**Comment by gleeda** [comment]
OK, I'm not sure if I have this all correct, but, here's how I got the cookie:

First I'm looking at `ntoskrnl.exe` and I see what instructions we have for `ObGetObjectType`: 

![screen shot 2017-06-22 at 2 32 56 pm](https://user-images.githubusercontent.com/176825/27449934-fe6e344e-5757-11e7-88f3-de8d4ccdf1fb.png)

Figured out where that is in memory, but using `yarascan`:

```
$ python vol.py -f Win10x64_14393.vmem --profile=Win10x64_14393 yarascan -K -Y "{48 8D 41 D0 0F B6 49 E8}"
Volatility Foundation Volatility Framework 2.6
Rule: r1
Owner: ntoskrnl.exe
0xf80176309d24  48 8d 41 d0 0f b6 49 e8 48 c1 e8 08 0f b6 c0 48   H.A...I.H......H
0xf80176309d34  33 c1 0f b6 0d 23 c7 eb ff 48 33 c1 48 8d 0d b9   3....#...H3.H...
0xf80176309d44  cb eb ff 48 8b 04 c1 c3 48 8b c4 48 89 58 08 48   ...H....H..H.X.H
```

Then investigate with `volshell`:

```
In [28]: addr = 0xf80176309d24

In [29]: dis(addr)
0xf80176309d24 488d41d0                         LEA RAX, [RCX-0x30]
0xf80176309d28 0fb649e8                         MOVZX ECX, BYTE [RCX-0x18]
0xf80176309d2c 48c1e808                         SHR RAX, 0x8
0xf80176309d30 0fb6c0                           MOVZX EAX, AL
0xf80176309d33 4833c1                           XOR RAX, RCX
0xf80176309d36 0fb60d23c7ebff                   MOVZX ECX, BYTE [RIP-0x1438dd]
0xf80176309d3d 4833c1                           XOR RAX, RCX
0xf80176309d40 488d0db9cbebff                   LEA RCX, [RIP-0x143447]
0xf80176309d47 488b04c1                         MOV RAX, [RCX+RAX*8]
0xf80176309d4b c3                               RET

[snip]

In [30]: for m in getmods():
    nt_mod = m
    break
   ....: 

In [31]: mode = distorm3.Decode64Bits

In [32]: data = nt_mod.obj_vm.read(addr, 100)

In [33]: ops = distorm3.Decompose(addr, data, mode, distorm3.DF_STOP_ON_RET)

In [34]: for op in reversed(ops):
    if (op.size == 7 and 'FLAG_RIP_RELATIVE' in op.flags and len(op.operands) == 2 and op.operands[0].type == 'Register' and
                                op.operands[1].type == 'AbsoluteMemory' and
                                op.operands[1].size == 8):
        addr2 = op.address + op.size + op.operands[1].disp
   ....:         

In [35]: nt_mod.obj_vm.is_valid_address(addr2)
Out[35]: True

In [36]: dis(addr2)
0xf801761c6460 87aedb4d0000                     XCHG [RSI+0x4ddb], EBP
0xf801761c6466 0000                             ADD [RAX], AL
0xf801761c6468 de01                             FIADD WORD [RCX]
[snip]

In [37]: cookie = obj.Object("unsigned int", offset = addr2, vm = nt_mod.obj_vm)

In [38]: hex(cookie)
Out[38]: '0x4ddbae87L'
```

**Comment by gleeda** [comment]
Ahhh ok... so that explains it :-)

**Comment by iMHLv2** [comment]
Sounds good...I'll de-prioritize a bit since you got it working, but will take care of the TypeError shortly.

**Comment by gleeda** [comment]
This is still an issue.  I keep coming across it with different Windows 10 machines...  I think I might have another way to get around this

**Comment by shpulka** [comment]
Hey. Is there any guide how to get value cookie?

**Comment by slackeater** [comment]
Hello, are there any updates on this issue? I have some Windows 2016 Server images  (profile is Win2016x64_14393) and I have the same problem. Is there a workaround to follow to allow pslist, psxview and the other to run?

**Comment by mydockergit** [comment]
@gleeda from where you brought this data: "{48 8D 41 D0 0F B6 49 E8}"?

**Comment by oold** [comment]
@mydockergit That's the disassembly from the ObGetObjectType function. You can see the function in the screenshot. The hex values are the first two instructions of that function.

**Comment by mydockergit** [comment]
@oold  The first line with the address in the screenshot is `0x1404ead24`.  
I don't understand what you mean by "without the bytes the ASM instructions translate to". I don't see anything related to `48 8D 41 D0 0F B6 49 E8` in the screenshot.

**Comment by mydockergit** [comment]
I have similar problem:
```
root@kali:~/Desktop# volatility -f desktop.raw --profile=Win10x64_15063 psscan
Volatility Foundation Volatility Framework 2.6
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
WARNING : volatility.debug    : Cannot find nt!ObGetObjectType
```

I saw #240 had similar issue so I tried to dump the ntoskrnl module using:
```
$ python vol.py -f [memdump] --profile [profile] moddump -r ntos -D [dumpdir]
```

But in my case it didn't do anything:
```
root@kali:~/Desktop# volatility -f desktop.raw --profile=Win10x64_15063 moddump -r ntos -D .
Volatility Foundation Volatility Framework 2.6
Module Base        Module Name          Result
------------------ -------------------- ------

````

**Comment by oold** [comment]
@mydockergit That's what I meant. The bytes corresponding to the instructions can't be seen in the screenshot, but what's fed into yarascan is exactly those bytes. If you look into the code of my pull request, you'll find this:
```
# 488d41d0 lea rax, qword ptr [rcx - 0x30]
# 0fb649e8 movzx ecx, byte ptr [rcx - 0x18]
```
If you want to fix your issue, you have three options:
- Follow gleeda's instructions. Just take the byte signature as-is. It should work fine. No need to extract the signature yourself. And yes, doing it manually is painful and takes a lot of time.
- Download the patch generated from my pull request from https://patch-diff.githubusercontent.com/raw/volatilityfoundation/volatility/pull/729.patch and use `git apply` to apply the patch to your local Volatility repo.
- Wait until/if my PR gets merged.

**Comment by mydockergit** [comment]
I download your branch (`issue-436`) and tried it but now I received a different error:  
```
root@kali:~/Desktop# git clone --single-branch --branch=issue-436 https://github.com/oold/volatility.git
Cloning into 'volatility'...

remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 18616 (delta 26), reused 14 (delta 7), pack-reused 18568
Receiving objects: 100% (18616/18616), 14.87 MiB | 1.38 MiB/s, done.
Resolving deltas: 100% (14553/14553), done.
root@kali:~/Desktop# 
root@kali:~/Desktop# cd volatility/
root@kali:~/Desktop/volatility# python vol.py -f desktop.raw --profile=Win10x64_15063 psscan
Volatility Foundation Volatility Framework 2.6.1
ERROR   : volatility.debug    : The requested file doesn't exist
```   

Not sure what is the issue

**Comment by oold** [comment]
Well, you changed your working directory to the checked out repo. The `desktop.raw` file you’re trying to scan probably isn’t in there.

________________________________

**Comment by mydockergit** [comment]
Okay, now I am not getting the error but I don't get any information about processes on the system, something weird. I think it is related to #741.  
```
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_15063 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_15063 pslist
Volatility Foundation Volatility Framework 2.6.1
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------
0xffffc88a0ba57540                      786732 39...9      0 -------- ------      0                                                              
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_15063 hivelist
Volatility Foundation Volatility Framework 2.6.1
Virtual            Physical           Name
------------------ ------------------ ----
root@kali:~/Desktop/volatility# 

```

**Comment by oold** [comment]
Are you sure you're using the correct profile?

**Comment by mydockergit** [comment]
This is the info from the `imageinfo`:  
```
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw imageinfo
Volatility Foundation Volatility Framework 2.6.1
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win10x64_17134, Win10x64_14393, Win10x64_10586, Win10x64_16299, Win2016x64_14393, Win10x64_17763, Win10x64_15063 (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : FileAddressSpace (/root/Desktop/desktop.raw)
                      PAE type : No PAE
                           DTB : 0x1aa000L
                          KDBG : 0xf800b87544f0L
          Number of Processors : 1
     Image Type (Service Pack) : 0
                KPCR for CPU 0 : 0xfffff800b76bd000L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2019-02-12 19:19:48 UTC+0000
     Image local date and time : 2019-02-12 11:19:48 -0800
```  

I tried all of the suggested profiles and all of them gave me the same results:  
```
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_17763 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win2016x64_14393 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_16299 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_10586 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_14393 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_17134 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_15063 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
```

I thought maybe the file is corrupted but the only command that gives me good results is the `getservicesids`:  
```
root@kali:~/Desktop/volatility# python vol.py -f /root/Desktop/desktop.raw --profile=Win10x64_15063 getservicesids
Volatility Foundation Volatility Framework 2.6.1
servicesids = { 
    'S-1-5-80-1580004045-3657569029-3054886754-3760858607-1347140441': 'ErrDev',
    'S-1-5-80-3666930311-739912689-1101093007-1147922636-412121971': 'tunmp',
    'S-1-5-80-376233901-499118290-773318279-1925188704-297947815': 'USBSTOR',
    'S-1-5-80-2400470686-1781479961-2091307112-2920730856-2901594176': 'SMSvcHost 3.0.0.0',
...
```

**Comment by mydockergit** [comment]
Also, worth to mention, when I use `strings`, I can see lots of data, files, event logs, lots of stuff related to the operating system, it seems that the file is valid but there is some problem to read it, and it only finds one process when you use `pslist`.

**Comment by mydockergit** [comment]
@oold you can ignore it, I just understood it was corrupted memory file. Thanks for your help!

**Comment by kbleich** [comment]
> @mydockergit That's what I meant. The bytes corresponding to the instructions can't be seen in the screenshot, but what's fed into yarascan is exactly those bytes. If you look into the code of my pull request, you'll find this:
> 
> ```
> # 488d41d0 lea rax, qword ptr [rcx - 0x30]
> # 0fb649e8 movzx ecx, byte ptr [rcx - 0x18]
> ```
> 
> If you want to fix your issue, you have three options:
> 
> * Follow gleeda's instructions. Just take the byte signature as-is. It should work fine. No need to extract the signature yourself. And yes, doing it manually is painful and takes a lot of time.
> * Download the patch generated from my pull request from https://patch-diff.githubusercontent.com/raw/volatilityfoundation/volatility/pull/729.patch and use `git apply` to apply the patch to your local Volatility repo.
> * Wait until/if my PR gets merged.

I know this is a pretty dated discussion - but can you elaborate on option #2 (downloading patch - command line syntax for example). I'm not having any luck applying this patch.

**Comment by oold** [comment]
@kbleich

1. Download the patch. Let's say to `C:\Users\example_user\Downloads\729.patch`.
2. Open a command line (e.g. Git Bash) inside the repository folder.
3. Apply the patch with `git apply "C:\Users\example_user\Downloads\729.patch"`.

**Comment by Egyras** [comment]
> @mydockergit That's what I meant. The bytes corresponding to the instructions can't be seen in the screenshot, but what's fed into yarascan is exactly those bytes. If you look into the code of my pull request, you'll find this:
> 
> ```
> # 488d41d0 lea rax, qword ptr [rcx - 0x30]
> # 0fb649e8 movzx ecx, byte ptr [rcx - 0x18]
> ```
> 
> If you want to fix your issue, you have three options:
> 
> * Follow gleeda's instructions. Just take the byte signature as-is. It should work fine. No need to extract the signature yourself. And yes, doing it manually is painful and takes a lot of time.
> * Download the patch generated from my pull request from https://patch-diff.githubusercontent.com/raw/volatilityfoundation/volatility/pull/729.patch and use `git apply` to apply the patch to your local Volatility repo.
> * Wait until/if my PR gets merged.

no luck.....

` vol.py -f /tmp/MEMORY.DMP --profile=Win10x64_15063 psscan
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                PID   PPID PDB                Time created                   Time exited
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
WARNING : volatility.debug    : Cannot find NT module
WARNING : volatility.debug    : Cannot find NT module
ERROR   : volatility.debug    : Cannot obtain nt!ObHeaderCookie value
`

**Comment by oold** [comment]
It's probably best to try this with Volatility 3. Volatility 2 has been abandoned and whatever is causing your issues here might be fixed in Volatility 3. It would probably be for the best if the Volatility maintainers tried to guide people towards the new version.
