### ISSUE TITLE
error when running yarascan with -y

### ISSUE THREAD

**Issue by darkquasar** [volatilityfoundation/volatility#448]
vol.py yarascan -y=apt_naikon.yar -f ../ramdump --profile Win2012R2x64

Getting this error: 
Volatility Foundation Volatility Framework 2.4
PyErr_Occurred() != NULL
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 127, in execute
    func(outfd, data)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/malware/malfind.py", line 283, in render_text
    for o, addr, hit, content in data:
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/malware/malfind.py", line 231, in calculate
    rules = self._compile_rules()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/malware/malfind.py", line 216, in _compile_rules
    rules = yara.compile(self._config.YARA_FILE)
yara.Error: (2, 'No such file or directory')

**Comment by wroersma** [comment]
Can you reproduce this error with the latest version of volatility? (2.6)

**Comment by iMHLv2** [comment]
The proper syntax is --yara-file=FILE or -y FILE (not -y=FILE)
