### ISSUE TITLE
Plugin: linux_recover_filesystem TypeError: an integer is required Profile: LinuxUbuntu1704x64

### ISSUE THREAD

**Issue by zathizh** [volatilityfoundation/volatility#462]
Hi,

Plugin linux_recover_filesystem failed with error "TypeError: an integer is required"

python vol.py --profile=LinuxUbuntu1704x64 -f ../mem.bin linux_recover_filesystem -D filesystem
Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/volatility/volatility/plugins/linux/common.py", line 67, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/home/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/volatility/volatility/plugins/linux/recover_filesystem.py", line 106, in render_text
    for (num_files) in data: 
  File "/home/volatility/volatility/plugins/linux/recover_filesystem.py", line 99, in calculate
    self._fix_metadata(file_path, file_dentry)
  File "/home/volatility/volatility/plugins/linux/recover_filesystem.py", line 50, in _fix_metadata
    os.chown(out_path, inode.i_uid, inode.i_gid)
TypeError: an integer is required

**Comment by gtcode** [comment]
Also experiencing this bug here.

C5 in the currently-running 2017 contest has a profile and lime file that repro's this issue when using: http://downloads.volatilityfoundation.org/releases/2.6/volatility-2.6.zip

**Comment by marcan2020** [comment]
Same here, on a Ubuntu 12.04.3 lime memory dump:
```
myuser@myhost:~/Tools/volatility$ python vol.py --profile=LinuxUbuntu16043x64 -f /home/myuser/ubuntu.lime linux_recover_filesystem -D /tmp/dump/test
Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "vol.py", line 192, in \<module\>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/myuser/volatility/volatility/plugins/linux/common.py", line 67, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/home/myuser/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/myuser/volatility/volatility/plugins/linux/recover_filesystem.py", line 106, in render_text
    for (num_files) in data:
  File "/home/myuser/volatility/volatility/plugins/linux/recover_filesystem.py", line 99, in calculate
    self._fix_metadata(file_path, file_dentry)
  File "/home/myuser/volatility/volatility/plugins/linux/recover_filesystem.py", line 50, in _fix_metadata
    os.chown(out_path, inode.i_uid, inode.i_gid)
TypeError: an integer is required`
```
