### ISSUE TITLE
Python error when making vtypes for 10.13.1 profile on Mac

### ISSUE THREAD

**Issue by avtalley65** [volatilityfoundation/volatility#472]
Output from my attempt:
$ python ~/Downloads/Tools/volatility-master/tools/mac/convert.py 10.13.1_17B48_x64.dwarfdump.converted > kernel.vtypes
Traceback (most recent call last):
  File "/Users/secadmin/Downloads/Tools/volatility-master/tools/mac/convert.py", line 562, in <module>
    main()
  File "/Users/secadmin/Downloads/Tools/volatility-master/tools/mac/convert.py", line 559, in main
    parse_dwarf()     
  File "/Users/secadmin/Downloads/Tools/volatility-master/tools/mac/convert.py", line 399, in parse_dwarf
    parser.feed_line(line)
  File "/Users/secadmin/Downloads/Tools/volatility-master/tools/mac/convert.py", line 132, in feed_line
    self.process_statement(**parsed)
  File "/Users/secadmin/Downloads/Tools/volatility-master/tools/mac/convert.py", line 250, in process_statement
    off = int(data['AT_data_member_location'])
ValueError: invalid literal for int() with base 10: 'x00'

**Comment by atcuno** [comment]
Hello,

Thank you for the report. This has been fixed now:

https://github.com/volatilityfoundation/volatility/commit/6157f32b695aeb80fcef1056744a0b5a52741a99#diff-d313dad4fa684f6a1a2a21511dca0683

Also, we have an official profile for that version of OS X that you can use:

https://github.com/volatilityfoundation/profiles/tree/master/Mac/10.13
