### ISSUE TITLE
dumpcerts plugin seems broken

### ISSUE THREAD

**Issue by nov3mb3r** [volatilityfoundation/volatility#474]
I execute 
`vol.py -f memory.dmp --profile=Win10x86 dumpcerts --dump-dir /home/username/`
and volatility crashes
```
Volatility Foundation Volatility Framework 2.6
Pid      Process          Address    Type                 Length   File                     Subject
-------- ---------------- ---------- -------------------- -------- ------------------------ -------
Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 4, in <module>
    __import__('pkg_resources').run_script('volatility==2.6', 'vol.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/EGG-INFO/scripts/vol.py", line 192, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/EGG-INFO/scripts/vol.py", line 183, in main
    command.execute()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/dumpcerts.py", line 268, in render_text
    for process, cert in data:
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/dumpcerts.py", line 180, in calculate
    for hit, address in scanner.scan():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/malware/malfind.py", line 142, in scan
    for match in BaseYaraScanner.scan(self, vad.Start, vad.Length):
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6-py2.7.egg/volatility/plugins/malware/malfind.py", line 114, in scan
    for moffset, _name, _value in match.strings:
AttributeError: 'str' object has no attribute 'strings'
```

**Comment by gleeda** [comment]
I have a feeling this is an issue with installing the incorrect version of `yara`.  Out of curiousity, were you able to get this working?
