### ISSUE TITLE
KeyError: '__int128 unsigned' with ARM64 Android

### ISSUE THREAD

**Issue by LeoColomb** [volatilityfoundation/volatility#478]
Running Volatility over a LiME dump of an ARM64 Android phone raises the following error:

```
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/leo/android/volatility/volatility/plugins/linux/common.py", line 67, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/home/leo/android/volatility/volatility/commands.py", line 116, in execute
    if not self.is_valid_profile(profs[self._config.PROFILE]()):
  File "/home/leo/android/volatility/volatility/plugins/overlays/linux/linux.py", line 217, in __init__
    obj.Profile.__init__(self, *args, **kwargs)
  File "/home/leo/android/volatility/volatility/obj.py", line 862, in __init__
    self.reset()
  File "/home/leo/android/volatility/volatility/plugins/overlays/linux/linux.py", line 230, in reset
    self.load_vtypes()
  File "/home/leo/android/volatility/volatility/plugins/overlays/linux/linux.py", line 267, in load_vtypes
    vtypesvar = dwarf.DWARFParser(dwarfdata).finalize()
  File "/home/leo/android/volatility/volatility/dwarf.py", line 71, in __init__
    self.feed_line(line)
  File "/home/leo/android/volatility/volatility/dwarf.py", line 162, in feed_line
    self.process_statement(**parsed) #pylint: disable-msg=W0142
  File "/home/leo/android/volatility/volatility/dwarf.py", line 226, in process_statement
    self.id_to_name[statement_id] = [self.base_type_name(data)]
  File "/home/leo/android/volatility/volatility/dwarf.py", line 125, in base_type_name
    return self.tp2vol[data['DW_AT_name'].strip('"')]
KeyError: '__int128 unsigned'
```

My command:
```shell
python vol.py --profile=Linuxmsm8952-cm-14_1x64 -f ~/lime.dmp linux_pslist
```

My target phone:
* [MSM8952](https://github.com/LineageOS/android_kernel_htc_msm8952/tree/cm-14.1/) under Lineage (former CyanogenMod) 14.1 / Android 7.1.

---
Adding that type in [`volatility/dwarf.py`](https://github.com/volatilityfoundation/volatility/blob/5cc5d2a2b8e42537d69706560b1b48e341b7f924/volatility/dwarf.py) obviously fixes the error:
```python
    tp2vol = {
        ...
        'sizetype' : 'unsigned long',
        '__int128 unsigned': 'unsigned long long',
    }
```

That said I'm not sure the statement is right because I next face the same error as seen in #413 
> No suitable address space mapping found

**Comment by xandfury** [comment]
@atcuno Any particular reason why this ticket was closed? :slightly_smiling_face: @LeoColomb Did you figure out where adding the said entry is valid or not. Facing the same issue here.

**Comment by LeoColomb** [comment]
@xandfury Sorry, I did not. And I don't really know why the issue has been closed.
