### ISSUE TITLE
vol.py doesnt work

### ISSUE THREAD

**Issue by k142094** [volatilityfoundation/volatility#502]
i did this:
git clone https://github.com/volatilityfoundation/volatility.git
apt-get install pcregrep libpcre++-dev python-dev -y
sudo python setup.py install

then i did this:
cd volatility
vol.py

to get this:
Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 57, in <module>
    import volatility.commands as commands
  File "/usr/local/lib/python2.7/site-packages/volatility/commands.py", line 33, in <module>
    from volatility.renderers.sqlite import SqliteRenderer
  File "/usr/local/lib/python2.7/site-packages/volatility/renderers/sqlite.py", line 22, in <module>
    import sqlite3
  File "/usr/local/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/lib/python2.7/sqlite3/dbapi2.py", line 28, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3

**Comment by gleeda** [comment]
What distro are you using?  It looks like you don't have sqlite3 installed.

**Comment by gleeda** [comment]
Did you manage to figure out what the issue was?

**Comment by gleeda** [comment]
I'm going to close this issue for now.  Feel free to reopen if you have more information.
