### ISSUE TITLE
crash running mac_dead_procs against MacHighSierra_10_13_4_17E202x64

### ISSUE THREAD

**Issue by johnmccash** [volatilityfoundation/volatility#512]
While analyzing a Mac memory dump obtained using the osxpmem kernel extension and Mac Rekall, using the mac_dead_procs plugin, I get the following error:

$ vol.py -f /mnt/hgfs/D/EnCase_Cases/Mac\ Malware/ilch-ml0066.img --profile=MacHighSierra_10_13_4_17E202x64  mac_dead_procs
Volatility Foundation Volatility Framework 2.6
Offset             Name                 Pid      Uid      Gid      PGID     Bits         DTB                Start Time
------------------ -------------------- -------- -------- -------- -------- ------------ ------------------ ----------
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/pslist.py", line 134, in render_text
    for proc in data:
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/dead_procs.py", line 40, in calculate
    for zone in zones:
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/list_zones.py", line 40, in calculate
    zone_ptr = obj.Object("Pointer", offset = first_zone_addr, vm = self.addr_space)
  File "/usr/lib/python2.7/dist-packages/volatility/obj.py", line 171, in Object
    offset = int(offset)
TypeError: int() argument must be a string or a number, not 'NoneType'

**Comment by johnmccash** [comment]
I get a similar error for mac_dead_sockets:

$ vol.py -f /mnt/hgfs/D/EnCase_Cases/Mac\ Malware/ilch-ml0066.img --profile=MacHighSierra_10_13_4_17E202x64  mac_dead_sockets
Volatility Foundation Volatility Framework 2.6
Proto  Local IP             Local Port Remote IP            Remote Port State     
------ -------------------- ---------- -------------------- ----------- ----------
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/common.py", line 48, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/dead_sockets.py", line 55, in render_text
    for socket in data:
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/dead_sockets.py", line 40, in calculate
    for zone in zones:
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/mac/list_zones.py", line 40, in calculate
    zone_ptr = obj.Object("Pointer", offset = first_zone_addr, vm = self.addr_space)
  File "/usr/lib/python2.7/dist-packages/volatility/obj.py", line 171, in Object
    offset = int(offset)
TypeError: int() argument must be a string or a number, not 'NoneType'
