### ISSUE TITLE
Struct ERROR in get_available_pages at line 300

### ISSUE THREAD

**Issue by seanmcfeely** [volatilityfoundation/volatility#628]
Using this version of the standalone: http://downloads.volatilityfoundation.org/releases/2.6/volatility_2.6_lin64_standalone.zip
I get the following:
```
$ vol.py -f testhost.memdmp imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
  File "vol.py", line 183, in main
  File "volatility/commands.py", line 147, in execute
  File "volatility/plugins/imageinfo.py", line 45, in render_text
  File "volatility/plugins/imageinfo.py", line 55, in calculate
  File "volatility/plugins/kdbgscan.py", line 164, in calculate
  File "volatility/plugins/overlays/windows/win8_kdbg.py", line 255, in generate_suggestions
  File "volatility/plugins/addrspaces/paged.py", line 133, in get_available_addresses
  File "volatility/plugins/addrspaces/amd64.py", line 300, in get_available_pages
struct.error: unpack requires a string argument of length 4096
Failed to execute script vo
```

Using the latest code from:
`$ git clone https://github.com/volatilityfoundation/volatility.git`
and installing with `sudo -E python setup.py install` 
I get the following:
```
$ vol.py -f testhost.memdmp imageinfo
Volatility Foundation Volatility Framework 2.6.1
INFO    : volatility.debug    : Determining profile based on KDBG search...
Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 4, in <module>
    __import__('pkg_resources').run_script('volatility==2.6.1', 'vol.py')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/EGG-INFO/scripts/vol.py", line 192, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/EGG-INFO/scripts/vol.py", line 183, in main
    command.execute()
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/imageinfo.py", line 45, in render_text
    for k, t, v in data:
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/imageinfo.py", line 55, in calculate
    suglist = [ s for s, _ in kdbgscan.KDBGScan.calculate(self)]
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/kdbgscan.py", line 164, in calculate
    for kdbg in obj.VolMagic(aspace).KDBG.generate_suggestions():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/overlays/windows/win8_kdbg.py", line 273, in generate_suggestions
    addresses = sorted(addr_space.get_available_addresses())
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/addrspaces/paged.py", line 133, in get_available_addresses
    for (offset, size) in self.get_available_pages():
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.6.1-py2.7.egg/volatility/plugins/addrspaces/amd64.py", line 300, in get_available_pages
    pt_entries = struct.unpack('<512Q', pt)
struct.error: unpack requires a string argument of length 4096
```

The host I'm dumping memory on is a Windows 10 64bit PC running in virtual box. I've obtained raw memory with CarbonBlack Responses built in memory dumping functionality, with winpmem-2.1.post4.exe, and with winpmem_1.6.2.exe. All resulting raw memory dumps give me the same result.

Does anyone know what the issue is?

**Comment by iMHLv2** [comment]
IIRC winpmem outputs memory in AFF4 format even when you ask for a raw sample. It also rarely generates usable samples on Windows 10, based on feedback from other users. I'd recommend capturing memory with Surge (https://www.volexity.com/products-overview/surge/). Its a command-line tool as well, so you shouldn't have issues integrating it with CB.

**Comment by seanmcfeely** [comment]
I will check out surge this afternoon but I believe you missed that I also obtained memory with CarbonBlack Response using whatever proprietary solution they have under the hood. CbR mem dumps have been reliable for us in the past. I get the same result though when running vol imageinfo on the result. I'll try a windows 7 system and see if the results differ, then update. Thanks!

**Comment by iMHLv2** [comment]
Last I heard, CB was packaging winpmem. If you get a usable windows 7 memory dump, you could confirm by inspecting the loaded drivers. Couple of other tips:

* Try using `kdbgscan --profile=<win10 profile>` instead of `imageinfo` if you just want to check validity of the memory sample. This won't fix the struct error, but assuming you have a legit sample, it will be faster and give you more useful info. 

* Make sure `distorm3` python module is installed.

* `volatility_2.6_lin64_standalone.zip` is older and won't have as many Win10 profiles as the master branch on github does.

**Comment by seanmcfeely** [comment]
@iMHLv2, it seems to work flawlessly when dumping memory on a windows 7 system. So I guess that confirms it's a problem with winpmem obtaining memory on a win 10 system.. lame.

Thanks for the help!

**Comment by iMHLv2** [comment]
@seanmcfeely Cool, thanks for the update. Just as a heads up, I wouldn't generalize all Windows 7 systems to be safe. There are fully patched Win7 systems, Win7 systems with lots of RAM, Win7 systems running on bare metal vs different hypervisors, Win7 systems with obscure hardware or software, etc. Check out Surge for reliable capture, you won't be disappointed.
