### ISSUE TITLE
Win10x64_17763 profile not working

### ISSUE THREAD

**Issue by nowembery** [volatilityfoundation/volatility#640]
I'm trying to run Volatility (downloaded & installed from GitHub) on a .vmem file for a Windows 10 (version 1809, build 17763.379) 64-bit VM (https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/).

imageinfo:
```
python vol.py -f "/home/test/MSEdge-Win10-VMware-Snapshot1.vmem" imageinfo
Volatility Foundation Volatility Framework 2.6.1
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win10x64_17134, Win10x64_10586, Win10x64_14393, Win10x64_16299, Win2016x64_14393, Win10x64_17763, Win10x64_15063 (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : FileAddressSpace (/home/remnux/MSEdge-Win10-VMware-Snapshot1.vmem)
                      PAE type : No PAE
                           DTB : 0x1aa002L
                          KDBG : 0xf8030e6095e0L
          Number of Processors : 1
     Image Type (Service Pack) : 0
                KPCR for CPU 0 : 0xfffff8030e008000L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2019-09-02 13:11:08 UTC+0000
     Image local date and time : 2019-09-02 06:11:08 -0700
```

kdbgscan --force doesn't find any valid KDBGs:
```
python vol.py -f "/home/test/MSEdge-Win10-VMware-Snapshot1.vmem" kdbgscan --force
Volatility Foundation Volatility Framework 2.6.1
**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf8030e6095e0
Offset (P)                    : 0x24095e0
KdCopyDataBlock (V)           : 0xf8030e4941b8
Block encoded                 : Yes
Wait never                    : 0xeb643c0038ed6d4
Wait always                   : 0x71dae1f96c8a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_14393
Version64                     : 0xf8030e60cdc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8030e619650 (0 processes)
PsLoadedModuleList            : 0xfffff8030e6259f0 (0 modules)
KernelBase                    : 0xfffff8030e20a000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8030e008000 (CPU 0)

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_17134 (6.4.17134 64bit)
Offset (V)                    : 0xf8030e6095e0
Offset (P)                    : 0x24095e0
KdCopyDataBlock (V)           : 0xf8030e4941b8
Block encoded                 : Yes
Wait never                    : 0xeb643c0038ed6d4
Wait always                   : 0x71dae1f96c8a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_17134
Version64                     : 0xf8030e60cdc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8030e619650 (0 processes)
PsLoadedModuleList            : 0xfffff8030e6259f0 (0 modules)
KernelBase                    : 0xfffff8030e20a000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8030e008000 (CPU 0)

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_10586 (6.4.10586 64bit)
Offset (V)                    : 0xf8030e6095e0
Offset (P)                    : 0x24095e0
KdCopyDataBlock (V)           : 0xf8030e4941b8
Block encoded                 : Yes
Wait never                    : 0xeb643c0038ed6d4
Wait always                   : 0x71dae1f96c8a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_10586
Version64                     : 0xf8030e60cdc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8030e619650 (0 processes)
PsLoadedModuleList            : 0xfffff8030e6259f0 (0 modules)
KernelBase                    : 0xfffff8030e20a000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8030e008000 (CPU 0)

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_16299 (6.4.16299 64bit)
Offset (V)                    : 0xf8030e6095e0
Offset (P)                    : 0x24095e0
KdCopyDataBlock (V)           : 0xf8030e4941b8
Block encoded                 : Yes
Wait never                    : 0xeb643c0038ed6d4
Wait always                   : 0x71dae1f96c8a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_16299
Version64                     : 0xf8030e60cdc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8030e619650 (0 processes)
PsLoadedModuleList            : 0xfffff8030e6259f0 (0 modules)
KernelBase                    : 0xfffff8030e20a000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8030e008000 (CPU 0)

**************************************************
Instantiating KDBG using: Unnamed AS Win2016x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf8030e6095e0
Offset (P)                    : 0x24095e0
KdCopyDataBlock (V)           : 0xf8030e4941b8
Block encoded                 : Yes
Wait never                    : 0xeb643c0038ed6d4
Wait always                   : 0x71dae1f96c8a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win2016x64_14393
Version64                     : 0xf8030e60cdc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8030e619650 (0 processes)
PsLoadedModuleList            : 0xfffff8030e6259f0 (0 modules)
KernelBase                    : 0xfffff8030e20a000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8030e008000 (CPU 0)

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_17763 (6.4.17763 64bit)
Offset (V)                    : 0xf8030e6095e0
Offset (P)                    : 0x24095e0
KdCopyDataBlock (V)           : 0xf8030e4941b8
Block encoded                 : Yes
Wait never                    : 0xeb643c0038ed6d4
Wait always                   : 0x71dae1f96c8a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_17763
Version64                     : 0xf8030e60cdc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8030e619650 (0 processes)
PsLoadedModuleList            : 0xfffff8030e6259f0 (0 modules)
KernelBase                    : 0xfffff8030e20a000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8030e008000 (CPU 0)

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_15063 (6.4.15063 64bit)
Offset (V)                    : 0xf8030e6095e0
Offset (P)                    : 0x24095e0
KdCopyDataBlock (V)           : 0xf8030e4941b8
Block encoded                 : Yes
Wait never                    : 0xeb643c0038ed6d4
Wait always                   : 0x71dae1f96c8a0
KDBG owner tag check          : True
Profile suggestion (KDBGHeader): Win10x64_15063
Version64                     : 0xf8030e60cdc0 (Major: 15, Minor: 17763)
Service Pack (CmNtCSDVersion) : 0
Build string (NtBuildLab)     : 17763.1.amd64fre.rs5_release.180
PsActiveProcessHead           : 0xfffff8030e619650 (0 processes)
PsLoadedModuleList            : 0xfffff8030e6259f0 (0 modules)
KernelBase                    : 0xfffff8030e20a000 (Matches MZ: True)
Major (OptionalHeader)        : 10
Minor (OptionalHeader)        : 0
KPCR                          : 0xfffff8030e008000 (CPU 0)
```

pslist with the profile Win10x64_17763:
```
python vol.py -f "/home/test/MSEdge-Win10-VMware-Snapshot1.vmem" --profile=Win10x64_17763 pslist
Volatility Foundation Volatility Framework 2.6.1
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit                          
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------
```

psxview:
```
python vol.py -f "/home/test/MSEdge-Win10-VMware-Snapshot1.vmem" --profile=Win10x64_17763 psxview
Volatility Foundation Volatility Framework 2.6.1
Offset(P)          Name                    PID pslist psscan thrdproc pspcid csrss session deskthrd ExitTime
------------------ -------------------- ------ ------ ------ -------- ------ ----- ------- -------- --------
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "/home/remnux/Desktop/volatility-master/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/malware/psxview.py", line 441, in render_text
    for offset, process, ps_sources in data:
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/malware/psxview.py", line 220, in calculate
    ps_sources['psscan'] = self.check_psscan()
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/malware/psxview.py", line 128, in check_psscan
    for p in filescan.PSScan(self._config).calculate())
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/malware/psxview.py", line 127, in <genexpr>
    return dict((PsXview.get_file_offset(p), p)
  File "/home/remnux/Desktop/volatility-master/volatility/poolscan.py", line 213, in scan
    cookie = obj.VolMagic(space).ObHeaderCookie.v()
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/overlays/windows/win10.py", line 280, in v
    return self.get_best_suggestion()
  File "/home/remnux/Desktop/volatility-master/volatility/obj.py", line 821, in get_best_suggestion
    for val in self.get_suggestions():
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/overlays/windows/win10.py", line 287, in get_suggestions
    for x in self.generate_suggestions():
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/overlays/windows/win10.py", line 292, in generate_suggestions
    store.findcookie(self.obj_vm)
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/overlays/windows/win10.py", line 200, in findcookie
    for mod in kdbg.modules():
  File "/home/remnux/Desktop/volatility-master/volatility/plugins/overlays/windows/kdbg_vtypes.py", line 52, in modules
    raise AttributeError("Could not list modules, please verify your --profile with kdbgscan")
AttributeError: Could not list modules, please verify your --profile with kdbgscan
```

I'm not sure what could be the issue.

**Comment by nowembery** [comment]
Fixed by adding the .vmsn file in the same folder as the .vmem file. 

https://github.com/cuckoosandbox/cuckoo/issues/1842
