### ISSUE TITLE
MemoryError on windows10 with Win10x64_18362 profile

### ISSUE THREAD

**Issue by gabbiano83** [volatilityfoundation/volatility#657]
I'm getting memory error during Windows 10 x64 2GB memory dumped from Esxi 6.7 using Win10x64_18362 profile:

```
Traceback (most recent call last):
  File "/opt/calamity/volatility/vol.py", line 192, in <module>
    main()
  File "/opt/calamity/volatility/vol.py", line 183, in main
    command.execute()
  File "/opt/calamity/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/opt/calamity/volatility/volatility/plugins/malware/malconfscan.py", line 94, in render_text
    for task, start, end, malname, memory_model, config_data in data:
  File "/opt/calamity/volatility/volatility/plugins/malware/malconfscan.py", line 84, in calculate
    for task, vad_base_addr, end, hit, memory_model, config_data in instance.calculate():
  File "/opt/calamity/volatility/volatility/plugins/malware/utils/datperscan.py", line 216, in calculate
    [+] Searching memory by Yara rules.
data = proc_addr_space.zread(vad_base_addr, end - vad_base_addr)
  File "/opt/calamity/volatility/volatility/addrspace.py", line 283, in zread
    return self._read(addr, length, True)
  File "/opt/calamity/volatility/volatility/addrspace.py", line 269, in _read
    return "".join(buff)
MemoryError
```

**Comment by atcuno** [comment]
Hello,

Based on your backtrace, this appears to be an issue with malconfscan:

https://github.com/JPCERTCC/MalConfScan/blob/master/utils/datperscan.py#L216

It seems they do not filter for large Vads in that code, which can cause MemoryErrors when large (many GB+) ranges are encountered. I am going to close this here, but you should file a new bug with the malconfscan authors. Feel free to link them to my comments here.
