### ISSUE TITLE
pip install distorm3 install fail on windows 10 and windows server 2019

### ISSUE THREAD

**Issue by HansChen6243** [volatilityfoundation/volatility#663]
Hi,

I tried to run volatility on Windows 10 and Windows server 2019, and error shows up when I install distorm3.
The error is in 
> File "c:\python27\lib\subprocess.py", line 266 shows as below

` needquote = (" " in arg) or ("\t" in arg) or not arg `
    `    if needquote:         `                                         
                `   result.append('"')`

I am not sure if I should modify these codes when installing a package... 
I also try "pip install distorm3" for volatility on Ubuntu 16.04, and nothing goes wrong.
Is there anyone have idea about this?
Thanks

> command-line:

C:\Users\Administrator>pip install distorm3

Collecting distorm3
  Using cached https://files.pythonhosted.org/packages/2c/e3/84a3a99904c368daa1de5e85a6e9cc07189e7f66cb1338a9ebf93fa051bd/distorm3-3.4.1.tar.gz
Installing collected packages: distorm3
  Running setup.py install for distorm3 ... error
    Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini\~1\\appdata\\local\\temp\\pip-build-3zgyta\\distorm3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\admini\~1\appdata\local\temp\pip-maseyf-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running custom_build
    searching for vcvarsall.bat
    Compiling with None
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admini\~1\appdata\local\temp\pip-build-3zgyta\distorm3\setup.py", line 323, in <module>
        main()
      File "c:\users\admini\~1\appdata\local\temp\pip-build-3zgyta\distorm3\setup.py", line 320, in main
        setup(**options)
      File "c:\python27\lib\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\python27\lib\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\python27\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python27\lib\distutils\command\install.py", line 563, in run
        self.run_command('build')
      File "c:\python27\lib\distutils\cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "c:\python27\lib\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\users\admini\~1\appdata\local\temp\pip-build-3zgyta\distorm3\setup.py", line 92, in run
        compile_vc('make/win32/distorm.sln', 'dll', bits)
      File "c:\users\admini\~1\appdata\local\temp\pip-build-3zgyta\distorm3\setup.py", line 67, in compile_vc
        sp.check_call(['call', bat, 'x86_amd64' if platform=='x64' else 'x86', '&&'] + msbuild, shell = True)
      File "c:\python27\lib\subprocess.py", line 185, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\python27\lib\subprocess.py", line 172, in call
        return Popen(*popenargs, **kwargs).wait()
      File "c:\python27\lib\subprocess.py", line 394, in __init__
        errread, errwrite)
      File "c:\python27\lib\subprocess.py", line 599, in _execute_child
        args = list2cmdline(args)
      File "c:\python27\lib\subprocess.py", line 266, in list2cmdline
        needquote = (" " in arg) or ("\t" in arg) or not arg
    TypeError: argument of type 'NoneType' is not iterable

    ----------------------------------------
Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\admini\~1\\appdata\\local\\temp\\pip-build-3zgyta\\distorm3\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\admini\~1\appdata\local\temp\pip-maseyf-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\admini\~1\appdata\local\temp\pip-build-3zgyta\distorm3\

**Comment by atcuno** [comment]
It seems like this is a bug in Python: https://github.com/manubot/manubot/issues/34

This is not something we can fix unfortunately
