### ISSUE TITLE
AL2 AWS Linux 2 Issue

### ISSUE THREAD

**Issue by Tankcon88** [volatilityfoundation/volatility#700]
Does Volatility support on AWS linux 2?  When running this command on the sift image I get a tarceback error. 
I am trying to run sudo vol.py --plugins=. --profile=Linuxprofile-4_14_173-137_228_amzn2_x86_64x64 -f al2-output-nocompress.lime linux_banner. But I get this error:
Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "/usr/bin/vol.py", line 192, in <module>
    main()
  File "/usr/bin/vol.py", line 183, in main
    command.execute()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/linux/common.py", line 64, in execute
    commands.Command.execute(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/volatility/commands.py", line 116, in execute
    if not self.is_valid_profile(profs[self._config.PROFILE]()):
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/overlays/linux/linux.py", line 216, in __init__
    obj.Profile.__init__(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/volatility/obj.py", line 862, in __init__
    self.reset()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/overlays/linux/linux.py", line 227, in reset
    self.load_vtypes()
  File "/usr/lib/python2.7/dist-packages/volatility/plugins/overlays/linux/linux.py", line 264, in load_vtypes
    vtypesvar = dwarf.DWARFParser(dwarfdata).finalize()
  File "/usr/lib/python2.7/dist-packages/volatility/dwarf.py", line 71, in __init__
    self.feed_line(line)
  File "/usr/lib/python2.7/dist-packages/volatility/dwarf.py", line 162, in feed_line
    self.process_statement(**parsed) #pylint: disable-msg=W0142
  File "/usr/lib/python2.7/dist-packages/volatility/dwarf.py", line 204, in process_statement
    self.vtypes[name] = [ int(data['DW_AT_byte_size'], self.base), {} ]
KeyError: 'DW_AT_byte_size'

**Comment by atcuno** [comment]
It seems like you are using an ancient version of Volatility as this issue was fixed back in 2016:

https://github.com/volatilityfoundation/volatility/commit/5afe6537e7576d895914a89a9bcc03589cdc55b0#diff-7326da16f58e061fcb9519ad0f0850f5

Please grab the latest source code version from here (github) and try again. Please re-open the ticket if you still have issues.
