### ISSUE TITLE
Imageinfo plugin fails suggesting profile for Windows2016 14393 memdumps

### ISSUE THREAD

**Issue by LordGarithm** [volatilityfoundation/volatility#769]
I have a problem to analyze with volatility a pair of memdumps which belong to Windows 2016x64 with the following builds:

-  **server07**: 14393.4046.amd64fre.rs1_release.201028-1803 
- **server01**: 14393.4104.amd64fre.rs1_release.201202-1742 

The memdumps were taken from the hyper visor - vmware snapshot (vmem and vmss taken) - and with surge directly from the VMs too. The volatility output is the same for the memdumps taken by both methods and for the both servers too. In addition, surge logs don’t show any error after taking the memory. For all these reasons I think this not related to problems taking the memdumps but in regard with the profile.

Moreover, when volatility is run with the documented profile for this build - [2.6-Win-Profiles](https://github.com/volatilityfoundation/volatility/wiki/2.6-Win-Profiles) -  there is no error message, but the list in pslist output is empty:

```
 $ python ~/volatility2/volatility/vol.py -f data.lime --profile Win2016x64_14393 pslist 
    Volatility Foundation Volatility Framework 2.6.1

 Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit 
    ------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------ 

```

On the other, when use imageinfo to get the profile from the dump there is not suggestions:

-	**Server 07:**

```
$ python ~/volatility2/volatility/vol.py imageinfo -f data.lime
Volatility Foundation Volatility Framework 2.6.1
INFO    : volatility.debug    : Determining profile based on KDBG search...

          Suggested Profile(s) : No suggestion (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : LimeAddressSpace (Unnamed AS)
                     AS Layer3 : FileAddressSpace 
                      PAE type : No PAE
                           DTB : 0x1ab002L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2020-12-18 13:09:49 UTC+0000
     Image local date and time : 2020-12-18 14:09:49 +0100
```
-	**Server 01:**

**SURGE**
```
$python ~/volatility2/volatility/vol.py imageinfo -f data.lime 
Volatility Foundation Volatility Framework 2.6.1
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : No suggestion (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : LimeAddressSpace (Unnamed AS)
                     AS Layer3 : FileAddressSpace 
                      PAE type : No PAE
                           DTB : 0x1ab002L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2020-12-17 17:10:40 UTC+0000
     Image local date and time : 2020-12-17 18:10:40 +0100
```

**VMEM** Both files vmem and vmss were present in the working folder. The files were by suspending the VM.
```
$python ~/volatility2/volatility/vol.py imageinfo -f 01.vmem
Volatility Foundation Volatility Framework 2.6.1
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : No suggestion (Instantiated with Win10x64_15063)
                     AS Layer1 : SkipDuplicatesAMD64PagedMemory (Kernel AS)
                     AS Layer2 : VMWareMetaAddressSpace (Unnamed AS)
                     AS Layer3 : FileAddressSpace 
                      PAE type : No PAE
                           DTB : 0x1ab002L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2020-12-17 15:51:48 UTC+0000
     Image local date and time : 2020-12-17 16:51:48 +0100
```
As I mentioned the behavior is pretty consistent regardless the memdumps coming from the ESX server or taken by surge from the machine.

Of course, other plugins don't work either. This is the output from psscan, it might suggest which metadata has to be fixed :

```
$ python ~/volatility2/volatility/vol.py -f data.lime --profile Win2016x64_14393 psscan
Volatility Foundation Volatility Framework 2.6.1

Offset(P)          Name                PID   PPID PDB                Time created                   Time exited                   
------------------ ---------------- ------ ------ ------------------ ------------------------------ ------------------------------
WARNING : volatility.debug    : distorm3 module is not installed
WARNING : volatility.debug    : distorm3 module is not installed
Traceback (most recent call last):
  File "/home/vicente/volatility2/volatility/vol.py", line 192, in <module>
    main()
  File "/home/vicente/volatility2/volatility/vol.py", line 183, in main
    command.execute()
  File "/home/vicente/volatility2/volatility/volatility/commands.py", line 147, in execute
    func(outfd, data)
  File "/home/vicente/volatility2/volatility/volatility/plugins/filescan.py", line 428, in render_text
    for eprocess in data:
  File "/home/vicente/volatility2/volatility/volatility/poolscan.py", line 252, in scan
    skip_type_check = skip_type_check)
  File "/home/vicente/volatility2/volatility/volatility/plugins/overlays/windows/windows.py", line 1258, in get_object
    return self.get_object_top_down(struct_name, object_type, skip_type_check)
  File "/home/vicente/volatility2/volatility/volatility/plugins/overlays/windows/windows.py", line 1231, in get_object_top_down
    header.get_object_type() == object_type):
  File "/home/vicente/volatility2/volatility/volatility/plugins/overlays/windows/win7.py", line 155, in get_object_type
    return self.type_map.get(int(self.TypeIndex), '')
  File "/home/vicente/volatility2/volatility/volatility/plugins/overlays/windows/win10.py", line 334, in TypeIndex
    return ((addr >> 8) ^ cook ^ indx) & 0xFF
TypeError: unsupported operand type(s) for ^: 'int' and 'NoneType'
```

Is there anyone having problems with recently patched memdumps from this build? Does anyone know any "esay modification" to fix the plugin?

**Comment by iMHLv2** [comment]
@LordGarithm "volatility.debug : distorm3 module is not installed" looks like you don't have the distorm3 module installed.

**Comment by LordGarithm** [comment]
Yes, this is the case. As far as I know this is only required to run some plugins when some x86 decoding is required (as apihooks and malfind). But, not for running pslist or psscan. Actualy, python doesn't fail to import psscan.

**Comment by LordGarithm** [comment]
OK, I am reviewing the documentation and I will install distorm3 rerun pslist and update the issue afterwards.

**Comment by LordGarithm** [comment]
OK, definitively decoding is required to pslist. the profile win2016x64_14393 works with my samples. Thanks!
