### ISSUE TITLE
Crypto.Hash module import error

### ISSUE THREAD

**Issue by sankethj** [volatilityfoundation/volatility#771]
root@kali:~/Desktop/tryhackme/vol_for# python /root/volatility/vol.py -f victim.raw --profile=Win7SP1x64 shellbags
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
ERROR   : volatility.debug    : You must specify something to do (try -h)

root@kali:~/Desktop/tryhackme/vol_for# pip install pycrypto
Requirement already satisfied: pycrypto in /usr/lib/python3/dist-packages (2.6.1)

I also reinstalled modules but still same error goes.

**Comment by 0x0ff** [comment]
Same.

**Comment by zin-htet-aung** [comment]
Check this.
https://jaseit.com/forensics/how-to-install-volatility-2-6in-kali-2020-4/

**Comment by slicetopieces** [comment]
link doesn't work

**Comment by R4v3nG** [comment]
$ git clone https://github.com/gdabah/distorm.git
cd distorm3
python setup.py build
sudo python setup.py build install

sudo apt-get install yara -y
wge thttps://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz
tar -xvzf pycrypto-2.6.1.tar.gz
cd pycrypto-2.6.1
python setup.py build
sudo python setup.py build install

**Comment by 0x171** [comment]
> $ git clone https://github.com/gdabah/distorm.git
> cd distorm3
> python setup.py build
> sudo python setup.py build install
> 
> sudo apt-get install yara -y
> wge thttps://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz
> tar -xvzf pycrypto-2.6.1.tar.gz
> cd pycrypto-2.6.1
> python setup.py build
> sudo python setup.py build install

Thanks for your solution. Now with your solution "(ImportError: No module named Crypto.Hash)" had solved.
but this error not solved yet

kali@kali:~/volatility$ sudo python vol.py install
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
ERROR   : volatility.debug    : You must specify something to do (try -h)
 
What should I do to run volatility without any problems?

**Comment by joncut99** [comment]
> > $ git clone https://github.com/gdabah/distorm.git
> > cd distorm3
> > python setup.py build
> > sudo python setup.py build install
> > sudo apt-get install yara -y
> > wge thttps://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz
> > tar -xvzf pycrypto-2.6.1.tar.gz
> > cd pycrypto-2.6.1
> > python setup.py build
> > sudo python setup.py build install
> 
> Thanks for your solution. Now with your solution "(ImportError: No module named Crypto.Hash)" had solved.
> but this error not solved yet
> 
> kali@kali:~/volatility$ sudo python vol.py install
> Volatility Foundation Volatility Framework 2.6.1
> *** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
> *** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
> *** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
> *** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
> *** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
> *** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
> ERROR : volatility.debug : You must specify something to do (try -h)
> 
> What should I do to run volatility without any problems?

This worked perfectly for me. Had to install the compiler for python.

**Comment by 0x171** [comment]
> > > $ git clone https://github.com/gdabah/distorm.git
> > > cd distorm3
> > > python setup.py build
> > > sudo python setup.py build install
> > > sudo apt-get install yara -y
> > > wge thttps://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz
> > > tar -xvzf pycrypto-2.6.1.tar.gz
> > > cd pycrypto-2.6.1
> > > python setup.py build
> > > sudo python setup.py build install
> > 
> > 
> > Thanks for your solution. Now with your solution "(ImportError: No module named Crypto.Hash)" had solved.
> > but this error not solved yet
> > kali@kali:~/volatility$ sudo python vol.py install
> > Volatility Foundation Volatility Framework 2.6.1
> > *** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
> > *** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
> > *** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
> > *** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
> > *** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
> > *** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
> > ERROR : volatility.debug : You must specify something to do (try -h)
> > What should I do to run volatility without any problems?
> 
> This worked perfectly for me. Had to install the compiler for python.

This happend when I try install distorm 

kali@kali:~/pyPackages/distorm$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import Extension, setup
ImportError: No module named setuptools
kali@kali:~/pyPackages/distorm$ sudo python setup.py build install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import Extension, setup
ImportError: No module named setuptools

I have already downloaded setuptools

**Comment by benjaminrobertbradley** [comment]
> $ git clone https://github.com/gdabah/distorm.git
> cd distorm3
> python setup.py build
> sudo python setup.py build install
> 
> sudo apt-get install yara -y
> wge thttps://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz
> tar -xvzf pycrypto-2.6.1.tar.gz
> cd pycrypto-2.6.1
> python setup.py build
> sudo python setup.py build install

Thanks, buddy!

**Comment by hack-phoenix** [comment]
> $ git clone https://github.com/gdabah/distorm.git
> cd distorm3
> python setup.py build
> sudo python setup.py build install
> 
> sudo apt-get install yara -y
> wge thttps://ftp.dlitz.net/pub/dlitz/crypto/pycrypto/pycrypto-2.6.1.tar.gz
> tar -xvzf pycrypto-2.6.1.tar.gz
> cd pycrypto-2.6.1
> python setup.py build
> sudo python setup.py build install

![ss](https://user-images.githubusercontent.com/82865927/115351062-f3958580-a209-11eb-85ed-084efb2fa745.png)


Hi I'm trying to install volatility for testing memory image but the setup was giving errors. When I tried your method I got this.
Please advise on how to proceed. Thanks :)

**Comment by joshuafoo** [comment]
@hack-phoenix use python3 not python2

**Comment by markasoftware** [comment]
You may need to install an older version of distorm3 for python 2

**Comment by ArjunaAcchaDipa** [comment]
Hi, I just found the solution yesterday. So try to run this in the terminal
```
1. pip install --upgrade setuptools
2. sudo apt-get install python-dev
3. pip2 install pycrypto && pip install distorm3
```

I you're already done with the crypto.hash, then on the line 3, try to run the `pip2 install distorm3`

**Comment by resteex0** [comment]
i have same issue 

Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)

**Comment by ArjunaAcchaDipa** [comment]
> i have same issue
> 
> Volatility Foundation Volatility Framework 2.6.1 *** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined) *** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined) *** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3) *** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3) *** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined) *** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash) *** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3) *** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)

Have you tried any of the solutions here?

**Comment by Stevefourier** [comment]
I have the same issue but with a windows machine.
C:\Users\Stephen\Downloads\volatility-master\volatility-master>C:\Python27\vol.py .\git clone https://github.com/volatilityfoundation/volatility.git
Volatility Foundation Volatility Framework 2.6.1
*** Failed to import volatility.plugins.registry.shutdown (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getservicesids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.timeliner (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.apihooks (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.malware.servicediff (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.userassist (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.getsids (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shellbags (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.evtlogs (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.tcaudit (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.dumpregistry (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.lsadump (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.malware.threads (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.mac.apihooks_kernel (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.registry.amcache (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.check_syscall_shadow (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.malware.svcscan (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.auditpol (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.ssdt (NameError: name 'distorm3' is not defined)
*** Failed to import volatility.plugins.registry.registryapi (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.mac.apihooks (ImportError: No module named distorm3)
*** Failed to import volatility.plugins.envars (ImportError: No module named Crypto.Hash)
*** Failed to import volatility.plugins.registry.shimcache (ImportError: No module named Crypto.Hash)
ERROR   : volatility.debug    : You must specify something to do (try -h)

How do i fix this please?

**Comment by secure-77** [comment]
This works for me to fix all the errors

Install system dependencies
```
sudo apt install -y build-essential git libdistorm3-dev yara libraw1394-11 libcapstone-dev capstone-tool tzdata
```
Install pip for Python 2
```
sudo apt install -y python2 python2.7-dev libpython2-dev
curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
sudo python2 get-pip.py
sudo python2 -m pip install -U setuptools wheel
```
Install Volatility 2 and its Python dependencies
```
python2 -m pip install -U distorm3 yara pycrypto pillow openpyxl ujson pytz ipython capstone
sudo python2 -m pip install yara
sudo ln -s /usr/local/lib/python2.7/dist-packages/usr/lib/libyara.so /usr/lib/libyara.so
python2 -m pip install -U git+https://github.com/volatilityfoundation/volatility.git
```

**Comment by phamleduy04** [comment]
> Hi, I just found the solution yesterday. So try to run this in the terminal
> 
> ```
> 1. pip install --upgrade setuptools
> 2. sudo apt-get install python2-dev
> 3. pip2 install pycrypto && pip install distorm3
> ```
> 
> I you're already done with the crypto.hash, then on the line 3, try to run the `pip2 install distorm3`. But if your pip2 giving you output `error: invalid command 'egg_info'`. Then try to download the pip2 using this
> 
> ```
> 1. curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py
> 2. sudo python2 /tmp/get-pip.py
> ```
> 
> After that try to re-run the first 3 command to install pycrypto and distorm3

thank you <3

**Comment by XKaguya** [comment]
> This works for me to fix all the errors
> 
> Install system dependencies
> 
> ```
> sudo apt install -y build-essential git libdistorm3-dev yara libraw1394-11 libcapstone-dev capstone-tool tzdata
> ```
> 
> Install pip for Python 2
> 
> ```
> sudo apt install -y python2 python2.7-dev libpython2-dev
> curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
> sudo python2 get-pip.py
> sudo python2 -m pip install -U setuptools wheel
> ```
> 
> Install Volatility 2 and its Python dependencies
> 
> ```
> python2 -m pip install -U distorm3 yara pycrypto pillow openpyxl ujson pytz ipython capstone
> sudo python2 -m pip install yara
> sudo ln -s /usr/local/lib/python2.7/dist-packages/usr/lib/libyara.so /usr/lib/libyara.so
> python2 -m pip install -U git+https://github.com/volatilityfoundation/volatility.git
> ```
> 
> from: https://seanthegeek.net/1172/how-to-install-volatility-2-and-volatility-3-on-debian-ubuntu-or-kali-linux/

Thank you :) its worked for me too

**Comment by cell13** [comment]
> > Hi, I just found the solution yesterday. So try to run this in the terminal
> > ```
> > 1. pip install --upgrade setuptools
> > 2. sudo apt-get install python2-dev
> > 3. pip2 install pycrypto && pip install distorm3
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I you're already done with the crypto.hash, then on the line 3, try to run the `pip2 install distorm3`. But if your pip2 giving you output `error: invalid command 'egg_info'`. Then try to download the pip2 using this
> > ```
> > 1. curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py
> > 2. sudo python2 /tmp/get-pip.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After that try to re-run the first 3 command to install pycrypto and distorm3
> 
> thank you <3

thanks

**Comment by felpostorm** [comment]
> This works for me to fix all the errors
> 
> Install system dependencies
> 
> ```
> sudo apt install -y build-essential git libdistorm3-dev yara libraw1394-11 libcapstone-dev capstone-tool tzdata
> ```
> 
> Install pip for Python 2
> 
> ```
> sudo apt install -y python2 python2.7-dev libpython2-dev
> curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
> sudo python2 get-pip.py
> sudo python2 -m pip install -U setuptools wheel
> ```
> 
> Install Volatility 2 and its Python dependencies
> 
> ```
> python2 -m pip install -U distorm3 yara pycrypto pillow openpyxl ujson pytz ipython capstone
> sudo python2 -m pip install yara
> sudo ln -s /usr/local/lib/python2.7/dist-packages/usr/lib/libyara.so /usr/lib/libyara.so
> python2 -m pip install -U git+https://github.com/volatilityfoundation/volatility.git
> ```
> 
> from: https://seanthegeek.net/1172/how-to-install-volatility-2-and-volatility-3-on-debian-ubuntu-or-kali-linux/

Worked for me!

**Comment by arm72** [comment]
thank you got it working thanks to you both: [ArjunaAcchaDipa](https://github.com/ArjunaAcchaDipa) & [secure-77](https://github.com/secure-77) !!!!!!

**Comment by Clementi11** [comment]
> 



> This works for me to fix all the errors
> 
> Install system dependencies
> 
> ```
> sudo apt install -y build-essential git libdistorm3-dev yara libraw1394-11 libcapstone-dev capstone-tool tzdata
> ```
> 
> Install pip for Python 2
> 
> ```
> sudo apt install -y python2 python2.7-dev libpython2-dev
> curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output get-pip.py
> sudo python2 get-pip.py
> sudo python2 -m pip install -U setuptools wheel
> ```
> 
> Install Volatility 2 and its Python dependencies
> 
> ```
> python2 -m pip install -U distorm3 yara pycrypto pillow openpyxl ujson pytz ipython capstone
> sudo python2 -m pip install yara
> sudo ln -s /usr/local/lib/python2.7/dist-packages/usr/lib/libyara.so /usr/lib/libyara.so
> python2 -m pip install -U git+https://github.com/volatilityfoundation/volatility.git
> ```
> 
> from: https://seanthegeek.net/1172/how-to-install-volatility-2-and-volatility-3-on-debian-ubuntu-or-kali-linux/

listen  to me! you! are! my! god!!!

**Comment by 05t3** [comment]
Hey.

After consolidating all those solutions above, I built an error-free docker image to resolve all issues.

You can find the image on docker hub :  [oste/volatility2](https://hub.docker.com/r/oste/volatility2)

Simply run:

```bash
docker run --rm oste/volatility2 volatility -h
```

If you care to build the image yourself, you can use the attached Dockerfile.

```docker
FROM ubuntu:22.10

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y git curl nano vim python2.7 wget pcregrep libpcre++-dev python2-dev build-essential libdistorm3-dev yara libraw1394-11 libcapstone-dev capstone-tool tzdata \
    && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py \
    && python2 get-pip.py \
    && pip2 install pycrypto distorm3 \
    && echo 'alias volatility="python2 /opt/volatility/vol.py"' >> /root/.bashrc \
    && git clone https://github.com/volatilityfoundation/volatility.git /opt/volatility

WORKDIR /opt/volatility

ENTRYPOINT ["python2", "vol.py"]
```

Enjoy 😉

**Comment by epaphrasmakoko** [comment]
> Hey.
> 
> After consolidating all those solutions above, I built an error-free docker image to resolve all issues.
> 
> You can find the image on docker hub : [oste/volatility2](https://hub.docker.com/r/oste/volatility2)
> 
> Simply run:
> 
> ```shell
> docker run --rm oste/volatility2 volatility -h
> ```
> 
> If you care to build the image yourself, you can use the attached Dockerfile.
> 
> ```
> FROM ubuntu:22.10
> 
> RUN apt-get update \
>     && DEBIAN_FRONTEND=noninteractive apt-get install -y git curl nano vim python2.7 wget pcregrep libpcre++-dev python2-dev build-essential libdistorm3-dev yara libraw1394-11 libcapstone-dev capstone-tool tzdata \
>     && curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py \
>     && python2 get-pip.py \
>     && pip2 install pycrypto distorm3 \
>     && echo 'alias volatility="python2 /opt/volatility/vol.py"' >> /root/.bashrc \
>     && git clone https://github.com/volatilityfoundation/volatility.git /opt/volatility
> 
> WORKDIR /opt/volatility
> 
> ENTRYPOINT ["python2", "vol.py"]
> ```
> 
> Enjoy 😉

let me look it around

**Comment by Randark-JMT** [comment]
pycryptodome might be a better choice

**Comment by AhmedHosniFahmi** [comment]
> Hi, I just found the solution yesterday. So try to run this in the terminal
> 
> ```
> 1. pip install --upgrade setuptools
> 2. sudo apt-get install python2-dev
> 3. pip2 install pycrypto && pip install distorm3
> ```
> 
> I you're already done with the crypto.hash, then on the line 3, try to run the `pip2 install distorm3`. But if your pip2 giving you output `error: invalid command 'egg_info'`. Then try to download the pip2 using this
> 
> ```
> 1. curl https://bootstrap.pypa.io/pip/2.7/get-pip.py --output /tmp/get-pip.py
> 2. sudo python2 /tmp/get-pip.py
> ```
> 
> After that try to re-run the first 3 command to install pycrypto and distorm3

TY!!!
