### ISSUE TITLE
Win10x64_14393 pslist is not showing anything

### ISSUE THREAD

**Issue by 12089897411** [volatilityfoundation/volatility#827]
C:\Users\Han\Desktop\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f 1.mem imageinfo
Volatility Foundation Volatility Framework 2.6
INFO    : volatility.debug    : Determining profile based on KDBG search...
          Suggested Profile(s) : Win10x64_14393, Win10x64_10586, Win10x64, Win2016x64_14393
                     AS Layer1 : Win10AMD64PagedMemory (Kernel AS)
                     AS Layer2 : FileAddressSpace (C:\Users\Han\Desktop\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone\1.mem)
                      PAE type : No PAE
                           DTB : 0x1ad002L
             KUSER_SHARED_DATA : 0xfffff78000000000L
           Image date and time : 2022-08-18 02:58:25 UTC+0000
     Image local date and time : 2022-08-18 10:58:25 +0800

C:\Users\Han\Desktop\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f 1.mem --profile=Win10x64_14393 pslist
Volatility Foundation Volatility Framework 2.6
Offset(V)          Name                    PID   PPID   Thds     Hnds   Sess  Wow64 Start                          Exit
------------------ -------------------- ------ ------ ------ -------- ------ ------ ------------------------------ ------------------------------

C:\Users\Han\Desktop\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>

C:\Users\Han\Desktop\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f 1.mem --profile=Win10x64_14393 kdbgscan
Volatility Foundation Volatility Framework 2.6
**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf8045fc7ca80
Offset (P)                    : 0x2e7ca80
KdCopyDataBlock (V)           : 0xf8045fd09168
Block encoded                 : No
Wait never                    : 0xfffff8045fbdc800
Wait always                   : 0xfffff8045f609960
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0xd08b49c08b49ca8b (0 processes)
PsLoadedModuleList            : 0xcccccccccccccccc (0 modules)
KernelBase                    : 0x8245c8b48198941 (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf804633e8e48
Offset (P)                    : 0x10e7ebe48
KdCopyDataBlock (V)           : 0xf804633e254d
Block encoded                 : No
Wait never                    : 0xfffff804633e8e48
Wait always                   : 0xfffff804633e8e48
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Version64                     : 0xf804633e8000 (Major: 0, Minor: 0)
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x0 (0 processes)
PsLoadedModuleList            : 0x0 (0 modules)
KernelBase                    : 0x0 (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf804640a8dd0
Offset (P)                    : 0x13a441dd0
KdCopyDataBlock (V)           : 0xf80464068899
Block encoded                 : No
Wait never                    : 0xfffff8045f216d20
Wait always                   : 0xc4334800055c0e05
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x6f6c6c417369644e (0 processes)
PsLoadedModuleList            : 0x0 (0 modules)
KernelBase                    : 0x4274654e65746163 (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf804648c82d0
Offset (P)                    : 0x104e662d0
KdCopyDataBlock (V)           : 0xf80464885099
Block encoded                 : Yes
Wait never                    : 0xfffff8045f2554d0
Wait always                   : 0xfffff8045f256040
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x7e708347e939b47 (0 processes)
PsLoadedModuleList            : 0xa7a4347e829b47 (0 modules)
KernelBase                    : 0xa7a7347e829b47 (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf8046493583e
Offset (P)                    : 0x104dd183e
KdCopyDataBlock (V)           : 0xf80464935782
Block encoded                 : Yes
Wait never                    : 0xfffff8045f253b50
Wait always                   : 0xfffff8045f253b50
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0xf62a6187f82c053 (0 processes)
PsLoadedModuleList            : 0xd11ad8336070023 (0 modules)
KernelBase                    : 0xcc2bea97b24e0c9b (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Unnamed AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf8046493587b
Offset (P)                    : 0x104dd187b
KdCopyDataBlock (V)           : 0xf804649357bf
Block encoded                 : Yes
Wait never                    : 0xfffff8045f253b50
Wait always                   : 0xfffff8045f3379b0
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0xfd187e17f58177ad (0 processes)
PsLoadedModuleList            : 0x8dad6edeace09aff (0 modules)
KernelBase                    : 0xaf2254fb1215bf (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf80464ba6a50
Offset (P)                    : 0x10753ba50
KdCopyDataBlock (V)           : 0xf80464ba2bb7
Block encoded                 : No
Wait never                    : 0xfffff80464ba6988
Wait always                   : 0xfffff8045f36ae80
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x67617373656d2074 (0 processes)
PsLoadedModuleList            : 0x6165706552206e65 (0 modules)
KernelBase                    : 0x746564207325206c (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf80464ba6a50
Offset (P)                    : 0x10753ba50
KdCopyDataBlock (V)           : 0xf80464ba2bc4
Block encoded                 : No
Wait never                    : 0xfffff80464ba6988
Wait always                   : 0xfffff8045f36ae80
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x67617373656d2074 (0 processes)
PsLoadedModuleList            : 0x6165706552206e65 (0 modules)
KernelBase                    : 0x746564207325206c (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf80464ba6a50
Offset (P)                    : 0x10753ba50
KdCopyDataBlock (V)           : 0xf80464ba2e0f
Block encoded                 : No
Wait never                    : 0xfffff80464ba69f0
Wait always                   : 0xfffff8045f36ae80
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x67617373656d2074 (0 processes)
PsLoadedModuleList            : 0x6165706552206e65 (0 modules)
KernelBase                    : 0x746564207325206c (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf80464ba6a50
Offset (P)                    : 0x10753ba50
KdCopyDataBlock (V)           : 0xf80464ba32bf
Block encoded                 : No
Wait never                    : 0xfffff80464ba69c0
Wait always                   : 0xfffff8045f36ae80
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x67617373656d2074 (0 processes)
PsLoadedModuleList            : 0x6165706552206e65 (0 modules)
KernelBase                    : 0x746564207325206c (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf80464ba6a50
Offset (P)                    : 0x10753ba50
KdCopyDataBlock (V)           : 0xf80464ba32cc
Block encoded                 : No
Wait never                    : 0xfffff80464ba69c0
Wait always                   : 0xfffff8045f36ae80
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x67617373656d2074 (0 processes)
PsLoadedModuleList            : 0x6165706552206e65 (0 modules)
KernelBase                    : 0x746564207325206c (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf8046539daa0
Offset (P)                    : 0x10e076aa0
KdCopyDataBlock (V)           : 0xf8046504003c
Block encoded                 : No
Wait never                    : 0xc7cb8b48d2330035
Wait always                   : 0x8f883647400000a
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x6f004300530043 (0 processes)
PsLoadedModuleList            : 0x6e006f004e0072 (0 modules)
KernelBase                    : 0xcccccccccc00656c (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf8046642819f
Offset (P)                    : 0xe50619f
KdCopyDataBlock (V)           : 0xf80466423806
Block encoded                 : No
Wait never                    : 0x0
Wait always                   : 0xfffff8046642a640
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x79726f7463657269 (0 processes)
PsLoadedModuleList            : 0x440080009e000040 (0 modules)
KernelBase                    : 0x6e6f6974617265 (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**************************************************
Instantiating KDBG using: Kernel AS Win10x64_14393 (6.4.14393 64bit)
Offset (V)                    : 0xf80468b07795
Offset (P)                    : 0x10709c795
KdCopyDataBlock (V)           : 0xf80468b075de
Block encoded                 : No
Wait never                    : 0x4800069bcd058d48
Wait always                   : 0x3ff4e00000000000
KDBG owner tag check          : False
Profile suggestion (KDBGHeader): Win10x64_14393
Service Pack (CmNtCSDVersion) : -
Build string (NtBuildLab)     : -
PsActiveProcessHead           : 0x840fde3b48000000 (0 processes)
PsLoadedModuleList            : 0x90249c8b48000001 (0 modules)
KernelBase                    : 0x4830244489483824 (Matches MZ: False)
Major (OptionalHeader)        : -
Minor (OptionalHeader)        : -

**Comment by 12089897411** [comment]
I tried the dumpit tool and the accessdata FTK imager tool to get the memory image

**Comment by 12089897411** [comment]
C:\Users\Han\Desktop\volatility_2.6_win64_standalone\volatility_2.6_win64_standalone>volatility_2.6_win64_standalone.exe -f 1.mem --profile=Win10x64_14393 filescan | findstr "password"
Volatility Foundation Volatility Framework 2.6
WARNING : volatility.debug    : Cannot find KDBG
WARNING : volatility.debug    : Cannot find KDBG
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
  File "vol.py", line 183, in main
  File "volatility\commands.py", line 147, in execute
  File "volatility\plugins\filescan.py", line 75, in render_text
  File "volatility\poolscan.py", line 252, in scan
  File "volatility\plugins\overlays\windows\windows.py", line 1141, in get_object
  File "volatility\plugins\overlays\windows\windows.py", line 1114, in get_object_top_down
  File "volatility\plugins\overlays\windows\win7.py", line 155, in get_object_type
  File "volatility\plugins\overlays\windows\win10.py", line 272, in TypeIndex
TypeError: unsupported operand type(s) for ^: 'long' and 'NoneType'
Failed to execute script vol
