### ISSUE TITLE
LookupError: unknown encoding: cp65001

### ISSUE THREAD

**Issue by PepperYouth** [volatilityfoundation/volatility#848]
```powershell
PS C:\Users\Admin> volatility_2.6_win64_standalone.exe -h
Volatility Foundation Volatility Framework 2.6
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
  File "vol.py", line 169, in main
  File "volatility\conf.py", line 262, in parse_options
  File "volatility\conf.py", line 97, in print_help
  File "optparse.py", line 1670, in print_help
LookupError: unknown encoding: cp65001
Failed to execute script vol
``` 
My powershell active code page is 65001. Does Volatility not support UTF-8?

**Comment by PepperYouth** [comment]
It works in cmd（Active code page: 936）, but how it works in powershell？I don‘t want to change my powershell's chcp.
