### ISSUE TITLE
各位大佬能帮我看下是什么原因吗，用filescan指令时扫到乱码就会报错

### ISSUE THREAD

**Issue by rookiebeimo** [volatilityfoundation/volatility#864]
0x000000007d8b2070      1      1 R--rwd \Device\HarddiskVolume1瞟?
Traceback (most recent call last):
  File "vol.py", line 192, in <module>
    main()
  File "vol.py", line 183, in main
    command.execute()
  File "E:\浏览器\volatility-master\volatility\commands.py", line 147, in execute
    func(outfd, data)
  File "E:\浏览器\volatility-master\volatility\plugins\filescan.py", line 82, in render_text
    str(file.file_name_with_device() or ''))
  File "E:\浏览器\volatility-master\volatility\commands.py", line 239, in table_row
    outfd.write(self.tablesep.join(reslist) + "\n")
IOError: [Errno 0] Error

**Comment by rookiebeimo** [comment]
![Uploading image.png…]()
