### ISSUE TITLE
'yara.StringMatch' object is not iterable

### ISSUE THREAD

**Issue by Sinak91** [volatilityfoundation/volatility#869]
Hello,  
I'm trying to use the TrueCrypt plugin for Linux and I enter the following command:  
```bash
python2 vol.py -f ../memdump-2/memdump-2.raw --profile=LinuxDebian_4_19_0-22-amd64_profilex64 linux_truecrypt_passphrase
```
But Volatility doesn't run and I get the following message:  
```
Volatility Foundation Volatility Framework 2.6.1  
Process          Pid      Address            Password  
---------------- -------- ------------------ --------  
Traceback (most recent call last):  
  File "vol.py", line 192, in <module>  
    main()  
  File "vol.py", line 183, in main  
    command.execute()  
  File "/cases/Case_Study/Forensik/volatility/volatility/plugins/linux/common.py", line 67, in execute  
    commands.Command.execute(self, *args, **kwargs)  
  File "/cases/Case_Study/Forensik/volatility/volatility/commands.py", line 147, in execute  
    func(outfd, data)  
  File "/cases/Case_Study/Forensik/volatility/volatility/plugins/linux/linux_truecrypt.py", line 143, in render_text  
    for (task, address, password) in data:  
  File "/cases/Case_Study/Forensik/volatility/volatility/plugins/linux/linux_truecrypt.py", line 133, in calculate  
    for address, password in scanner.scan():  
  File "/cases/Case_Study/Forensik/volatility/volatility/plugins/linux/linux_truecrypt.py", line 60, in scan  
    vma.vm_end - vma.vm_start):  
  File "/cases/Case_Study/Forensik/volatility/volatility/plugins/malware/malfind.py", line 114, in scan  
    for moffset, _name, _value in match.strings:  
TypeError: 'yara.StringMatch' object is not iterable
```

**Comment by mischw** [comment]
I think this might be the issue: https://github.com/volatilityfoundation/volatility3/issues/932
Using yara 4.2.3 still works for me
