### ISSUE TITLE
linux_find_file --> OverflowError: range() result has too many items

### ISSUE THREAD

**Issue by fpusersuggest** [volatilityfoundation/volatility#99]
Hi, I have a new issue, it concern  linux_find_file plugin.

    
    user@localhost volatility-master07102014$ ./vol.py linux_find_file -F "/proc/7301/89"
    Volatility Foundation Volatility Framework 2.4
    Inode Number          Inode File Path
    ---------------- ---------- ---------
      1119547283 0xe38ee488 /proc/7301/89

    user@localhost volatility-master07102014$ ./vol.py linux_find_file -i 0xe38ee488 -O test.proc
    Volatility Foundation Volatility Framework 2.4
    Traceback (most recent call last):
      File "./vol.py", line 192, in <module>
        main()
      File "./vol.py", line 183, in main
        command.execute()
      File "/home/user/VOLATILITY/volatility-master07102014/volatility/plugins/linux/common.py", line     62, in execute
        commands.Command.execute(self, *args, **kwargs)
      File "/home/user/VOLATILITY/volatility-master07102014/volatility/commands.py", line 127, in   execute
        func(outfd, data)
      File "/home/user/VOLATILITY/volatility-master07102014/volatility/plugins/linux/find_file.py", line   142, in render_text
        for (file_path, inode) in data:
      File "/home/user/VOLATILITY/volatility-master07102014/volatility/plugins/linux/find_file.py", line 131, in calculate
        for page in self.get_file_contents(inode):        
      File "/home/user/VOLATILITY/volatility-master07102014/volatility/plugins/linux/find_file.py", line 235, in get_file_contents
        for idx in range(0, idxs):
    OverflowError: range() result has too many items
    user@localhost volatility-master07102014$

**Comment by atcuno** [comment]
Fixed by: https://github.com/volatilityfoundation/volatility/commit/c1fc9a74d5ab971d8eb71bbe8e3af3870fbfbe44
